CONTRIBUTING.md

docs: 修正文档笔误

---

src/dialog/demos/mobile.vue
src/dialog/dialog.vue
src/dialog/index.ts
test/ssr/__snapshots__/ssr.test.js.snap

fix: 弹出框蒙层点击是否关闭修复 & provide暴露$dialog, close #12

---

src/count-down/count-down.vue
src/count-down/demos/base.vue
src/count-down/demos/mobile.vue
src/count-down/demos/specs.vue
src/count-down/index.ts
src/count-down/props.ts
src/count-down/type.ts
test/ssr/__snapshots__/ssr.test.js.snap

feat: 支持主题和大小

---

src/back-top/demos/mobile.vue

feat: 优化backtop组件的demo

---

site/docs.config.js
src/components.ts
src/dropdown-menu/dropdown-item.vue
test/ssr/__snapshots__/ssr.test.js.snap

- fix(site): 恢复隐藏的 dropdown-menu 组件
- style(dropdown-menu): 优化一处循环生成的 DOM 结构

feat(dropdown-menu): 移除冗余的dom结构

---

src/pull-down-refresh/props.ts
src/pull-down-refresh/pull-down-refresh.md
src/pull-down-refresh/type.ts

- fix(pull-down-refresh): 更新props和md文件

feat: 更新props和md文件

---

src/count-down/count-down.vue
test/ssr/__snapshots__/ssr.test.js.snap

fix: 单位样式bug

---

site/docs.config.js
src/components.ts
src/dropdown-menu/dropdown-item.vue
test/ssr/__snapshots__/ssr.test.js.snap

- feat(dropdown-menu): 完善 dropdown-menu 组件的模板类型检查

feat(dropdown-menu): 完善 dropdown-menu 组件的模板类型检查

---

src/common.ts
src/upload/props.ts
src/upload/type.ts
src/upload/upload.md
src/upload/upload.vue
test/ssr/__snapshots__/ssr.test.js.snap

- fix(upload): 修复upload组件的各种类型报错

feat: 修复upload组件的各种类型报错

---

.github/workflows/pr-spelling.template.yml

ci: add pr-spelling

---

scripts/test/generate-coverage.js
site/styles/vars.less
site/web/plugin-tdoc/transforms.js
src/checkbox/demos/group.vue
src/checkbox/demos/mobile.vue
src/dialog/demos/input.vue
src/dropdown-menu/demos/mobile.vue
src/dropdown-menu/demos/tree-menu.vue
src/image/demos/position.vue
src/picker/demos/base.vue
src/picker/demos/cascade.vue
src/picker/picker.vue
src/shared/useDefault/index.ts
src/slider/slider.vue
src/textarea/textarea.vue
test/ssr/__snapshots__/ssr.test.js.snap

feat: 处理新加入的ci拼写检查报错

---

src/shared/useCountDown/index.ts
src/shared/useCountDown/utils.ts
src/tab-bar/demos/text-spread.vue
test/ssr/__snapshots__/ssr.test.js.snap

倒计时加入fps获取

---

CHANGELOG.md
package.json
test/ssr/__snapshots__/ssr.test.js.snap

feat: 0.8.1版本发布

---

src/tabs/demos/mobile.vue
src/tabs/tabs.vue
test/ssr/__snapshots__/ssr.test.js.snap

https://github.com/Tencent/tdesign-mobile-vue/issues/42
以及label需要支持slot的方式
- fix(tabs): label新增支持slot的方式

 fix(tabs): label支持动态修改，以及新增支持slot的方式

---

src/popup/demos/mobile.vue
src/popup/popup.md
src/popup/popup.vue
src/popup/props.ts
test/ssr/__snapshots__/ssr.test.js.snap

https://github.com/Tencent/tdesign-mobile-vue/issues/64
- fix(Popup): 修复teleport失效问题 #64

fix(popup): 修复teleport失效问题 #64

---

CHANGELOG.md
package.json

feat: 0.8.2发版

---

package.json
src/input/input.vue
src/search/demos/mobile.vue
src/search/search.vue
src/shared/component.ts
src/textarea/textarea.vue
test/ssr/__snapshots__/ssr.test.js.snap

fix(input): missing compositionend

---

src/swiper/demos/async.vue
src/swiper/demos/mobile.vue
src/swiper/swiper-item.vue
src/swiper/swiper.vue
test/ssr/__snapshots__/ssr.test.js.snap

fix: 动态列表处理

---

src/list/demos/pull-refresh.vue

- fix(list): 修复list的demo无法运行的问题

fix: 修改list的demo

---

src/action-sheet/action-sheet.md
src/action-sheet/props.ts
src/action-sheet/type.ts
src/avatar/avatar.md
src/avatar/type.ts
src/common.ts
src/dialog/dialog.md
src/dialog/props.ts
src/dialog/type.ts
src/grid/grid-item-props.ts
src/grid/grid.md
src/grid/props.ts
src/grid/type.ts
src/tab-bar/tab-bar.md
src/tab-bar/type.ts

feat: 更新多个组件的type.ts文件

---

CHANGELOG.md
package.json

fix: 0.8.4发版

---

src/textarea/textarea.vue

style(textarea): update style

---

src/textarea/demos/autosize.vue
src/textarea/demos/events.vue
src/textarea/demos/label.vue
src/textarea/demos/maxcharacter.vue
src/textarea/demos/maxlength.vue
src/textarea/demos/mobile.vue
src/textarea/demos/type.vue
src/textarea/textarea.vue
test/ssr/__snapshots__/ssr.test.js.snap

[https://github.com/Tencent/tdesign-mobile-vue/issues/95](url)
- feat(textarea): support label && update style

feat(textarea): support label && update style

---

src/indexes/demos/demo-indexes.vue
src/indexes/demos/mobile.vue
test/ssr/__snapshots__/ssr.test.js.snap

feat(indexes): 补充indexes组件的示例

---

site/web/app.vue

feat: 站点支持搜索

---

src/badge/badge.vue
src/collapse/collapse-panel.vue
src/textarea/textarea.vue

#124 
- fix(Badge): 修复 Badge 组件设置 color 属性无效问题

fix: 修复 Badge 组件设置 color 属性无效问题

---

site/docs.config.js

- fix(indexes): 左边菜单栏增加indexes组件

feat: 左边菜单栏增加indexes

---

package.json

feat: 升级publish-cli

---

CHANGELOG.md
package.json

feat: 0.8.6版本发布

---

src/search/search.md

- fix(Search): 修改组件文档,与实际功能保持一致

fix: 修改Search组件文档,与实际功能保持一致

---

src/badge/badge.vue
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/badge/__snapshots__/props.test.js.snap

https://github.com/Tencent/tdesign-mobile-vue/issues/118

修复 issue#118 Badge 组件 showZero 属性无效的问题

---

src/dropdown-menu/dropdown-item.vue

fixed  https://github.com/Tencent/tdesign-mobile-vue/issues/114
- fix(dropdown-menu): 修复单选update:value 失效的问题

fix: 修复单选update:value 失效的问题

---

site/docs.config.js

feat: 修改Dialog组件文案

---

src/dropdown-menu/dropdown-menu.md

#177 
方案：参考[小程序端](https://tdesign.tencent.com/miniprogram/components/dropdown-menu?tab=api)，`activeColor`属性处于【讨论中】阶段，所以目前先在文档中补充【讨论中】字样。
- docs(dropdown-menu): description of supplementary activeColor attribute

docs(dropdown-menu): description of supplementary activeColor attribute

---

package.json

fix: update package repository url

---

src/badge/badge.vue
src/cell/cell.vue
src/cell/demos/border.vue
src/cell/demos/click.vue
src/cell/demos/group.vue
src/cell/demos/mobile.vue
src/cell/demos/multiple.vue
src/cell/demos/single.vue
test/ssr/__snapshots__/ssr.test.js.snap
test/unit/badge/__snapshots__/props.test.js.snap
test/unit/cell/__snapshots__/props.test.js.snap

#168 
- fix(cell): support image attribute

fix(cell): support image attribute

---

site/styles/mobile/components.less
src/dialog/demos/mobile.vue
src/dialog/dialog.md
src/dialog/dialog.vue
test/ssr/__snapshots__/ssr.test.js.snap

resolve #173 
- feat(dialog): 支持 confirmBtn 和 cancelBtn 的插槽
- feat(dialog): 支持 actions 和 preventScrollThrough 属性

fix(dialog): enable props: actions & preventScrollThrough

---

src/fab/demos/display.vue
src/fab/demos/mobile.vue
src/fab/demos/text.vue
src/fab/fab.md
src/fab/fab.vue
src/fab/props.ts
src/fab/type.ts
test/ssr/__snapshots__/ssr.test.js.snap

#154 
#155 
- feat(fab): 支持buttonProps和style

feat(fab): update api && align design

---

src/message/message.md
src/message/props.ts
src/message/type.ts

docs(message): update API docs

---

src/list/demos/mobile.vue
src/list/list.md
src/list/list.vue
src/list/props.ts
src/list/type.ts
test/ssr/__snapshots__/ssr.test.js.snap

#170 
对齐list demo的设计稿
- fix(list): 更新list demo

fix(list): update list demo

---

src/upload/upload.md

fix(upload): fix docs error

---

src/dropdown-menu/dropdown-item.vue

fix(dropdown-menu): using correct style

---

src/dropdown-menu/dropdown-menu.md
src/dropdown-menu/dropdown-menu.vue

无
增加 toggle 方法主动切换菜单
DropdownMenu: 增加 toggle 方法主动切换菜单

feat(dropdown-menu): add toggle function

---

site/docs.config.js

docs: update component category

---

src/message/index.ts

修复 message 插件调用的类型提示
fix(message): 修复 message 插件调用的类型提示

fix(message): add missing MessageApi type

---

src/search/search.vue

fix #255
[Search组件失去焦点问题](https://github.com/Tencent/tdesign-mobile-vue/issues/255)
输入文本后，input失去焦点会隐藏已输入文本，同时清除按钮无法使用
- fix(search): 修复失去焦点后输入内容被隐藏和清除按钮无法使用的问题

fix(search): fix onblur and clear input

---

src/popup/popup.vue
test/snap/__snapshots__/csr.test.js.snap

无
修复Popup 使用 overlay 时没有传入 visible 必传属性的问题
- fix(Popup): 修复使用 overlay 组件没传入 visible 导致告警的问题

fix(popup): resolve warning about overlay visible

---

src/dialog/dialog.vue
test/snap/__snapshots__/csr.test.js.snap

fix #246 
- fix(Dialog): 修复 slot 渲染逻辑

fix(dialog): resolve slot correctly

---

src/textarea/textarea.vue

- fix(Textarea): 修复onchange事件会执行两次的问题

fix: 修复textarea组件onchange事件会执行两次的问题

---

src/image/image.vue

fix #263
[image组件响应性问题](https://github.com/Tencent/tdesign-mobile-vue/issues/263)
- fix(Image): 修复 src 变更没有重新渲染的问题

fix(image): fix responsiveness problem

---

src/pull-down-refresh/pull-down-refresh.vue

fix #267
- fix(PulldownRefresh): 修复下拉时偶尔失效的问题

fix(pulldown-refresh): enable touch move

---

CHANGELOG.md
package.json

feat: 0.10.3版本发布

---

src/search/__test__/__snapshots__/demo.test.jsx.snap
src/search/search.vue

fix #291
[搜索框类型默认为Search](https://github.com/Tencent/tdesign-mobile-vue/issues/291)
- feat(Search): 内嵌 input 组件 type 调整为 search

feat(search): add search type property

---

site/web/test-coverage.js
src/switch/__test__/__snapshots__/demo.test.jsx.snap
src/switch/__test__/index.test.jsx
src/switch/demos/base.vue
src/switch/demos/desc.vue
src/switch/demos/disabled.vue
src/switch/demos/mobile.vue

- feat(Switch): 更新示例代码
- feat(Switch): 新增单元测试

test: add unit test for switch

---

src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/dialog/dialog.vue

fix #300
- fix(Dialog): 修复 content 变更没有响应的问题

fix(dialog): fix content responsive problem

---

CHANGELOG.md
package.json

feat: 0.10.5发版

---

src/image-viewer/__test__/__snapshots__/index.test.jsx.snap
src/image-viewer/__test__/index.test.jsx
src/image-viewer/__test__/touch.ts
src/image-viewer/demos/mobile.vue
src/image-viewer/image-viewer.vue
src/swiper/swiper.vue

[tdesign-mobile-vue#271](https://github.com/Tencent/tdesign-mobile-vue/issues/271)
模拟 touch 系列事件时使用了部分开源的工具代码，后续可以考虑放在统一的文件夹
- test(image-viewer): 添加 image-viewer 的单元测试

test(image-viewer): add unit test for image-viewer

---

src/dialog/__test__/index.test.jsx

test: add unit test for dialog

---

src/collapse/demos/action.vue
src/pull-down-refresh/__test__/__snapshots__/index.test.jsx.snap
src/pull-down-refresh/__test__/index.test.jsx
src/pull-down-refresh/__test__/utils.ts
src/pull-down-refresh/demos/mobile.vue
src/pull-down-refresh/pull-down-refresh.vue

[mobile-vue#271](https://github.com/Tencent/tdesign-mobile-vue/issues/271?target=pull-down-refresh)
- test(PullDownRefresh): 添加单元测试

test(PullDownRefresh): add unit test

---

src/image-viewer/image-viewer.vue
src/upload/__test__/index.test.jsx
src/upload/demos/mobile.vue
src/upload/upload.vue

[tdesign-mobile-vue#271](https://github.com/Tencent/tdesign-mobile-vue/issues/271)
- feat(upload): 新增单元测试
- fix(upload): 修复上传失败后，再次上传会产生报错的问题

test(upload): add unit test for upload

---

src/slider/__test__/__snapshots__/demo.test.jsx.snap
src/slider/__test__/index.test.jsx
src/slider/demos/base.vue
src/slider/demos/disable.vue
src/slider/demos/mark.vue
src/slider/demos/mobile.vue
src/slider/demos/range.vue
src/slider/demos/value.vue
src/slider/slider.vue

#362
- fix(Slider): 修复 `label` 属性无效的问题
- feat(Slider): 新增单元测试

fix(Slider): complete the label attribute && add test unit

---

CHANGELOG.md
src/calendar/__test__/__snapshots__/demo.test.jsx.snap
src/calendar/__test__/demo.test.jsx
src/pull-down-refresh/__test__/__snapshots__/demo.test.jsx.snap
src/tabs/__test__/__snapshots__/demo.test.jsx.snap
src/tabs/__test__/__snapshots__/index.test.jsx.snap
src/tabs/__test__/demo.test.jsx
src/tabs/__test__/index.test.jsx
src/tabs/demos/animation.vue
src/tabs/demos/base.vue
src/tabs/demos/disabled.vue
src/tabs/demos/mobile.vue
src/tabs/demos/size.vue
src/tabs/demos/underscore.vue
src/tabs/demos/vertical.vue
src/tabs/tab-panel.vue
src/tabs/tabs.vue

- fix(Tabs): 修复 `change` 事件和 `onChange` 属性无效的问题

fix(Tabs): fix change event and props.onChange are invalid

---

src/grid/__test__/__snapshots__/demo.test.jsx.snap
src/grid/__test__/index.test.jsx
src/grid/demos/badge.vue
src/grid/demos/base.vue
src/grid/demos/desc.vue
src/grid/demos/mobile.vue
src/grid/grid-item.vue

- fix(Grid): 修复 `gutter` 无效
- fix(Grid): 修复 `border` 无效
- test(Grid): 提升测试覆盖率

test: improve unit test coverage

---

src/divider/__test__/__snapshots__/demo.test.jsx.snap
src/divider/__test__/index.test.jsx
src/divider/demos/align.vue
src/divider/demos/base.vue
src/divider/demos/horizontal.vue
src/divider/demos/mobile.vue
src/divider/demos/vertical.vue

- test(Divider): 提升测试覆盖率
- feat(Divider): 更是示例代码

test(Divider): improve unit test coverage

---

src/steps/__test__/__snapshots__/index.test.jsx.snap
src/steps/__test__/index.test.jsx

test(Steps): add unit test for steps

---

src/dropdown-menu/__test__/__snapshots__/index.test.jsx.snap
src/dropdown-menu/__test__/index.test.jsx
src/dropdown-menu/dropdown-item.vue

- fix(DropdownMenu): 修复 `onChange` 事件无效的问题
- feat(DropdownMenu): 新增单元测试

fix(DropdownMenu): fix the onChange event is invalid

---

src/badge/__test__/index.test.jsx

test(Badge): improve unit test coverage

---

src/radio/__test__/__snapshots__/index.test.jsx.snap
src/radio/__test__/index.test.jsx

test(Radio): improve unit test coverage

---

src/notice-bar/__test__/__snapshots__/demo.test.jsx.snap
src/notice-bar/__test__/index.test.jsx
src/notice-bar/notice-bar.md
src/notice-bar/notice-bar.vue

fix #301
[content slot 无效](https://github.com/Tencent/tdesign-mobile-vue/issues/301)
需要注意的是，文档中的“suffixIcon"和“prefixIcon”已修改为"suffix-icon"和“prefix-icon”，否则在slot中无法生效
- fix(NoticeBar): 修复 content、extra 失效的问题

fix(noticebar): fix slot problem and add unit test

---

site/docs.config.js
src/cascader/cascader-item-prop.ts
src/cascader/cascader-item.vue
src/cascader/cascader.md
src/cascader/cascader.vue
src/cascader/demos/base.vue
src/cascader/demos/mobile.vue
src/cascader/index.ts
src/cascader/props.ts
src/cascader/style/css.js
src/cascader/style/index.js
src/cascader/type.ts
src/components.ts

#234 
- fix(cascader): feat(cascader): 添加了cascader组件基本API

feat(cascader): 添加了cascader组件基本API

---

src/notice-bar/__test__/index.test.jsx
src/notice-bar/notice-bar.vue

- fix(NoticeBar): 使用正确的 prefixIcon 插槽名

fix(NoticeBar): use the correct slot name

---

src/overlay/overlay.md
src/overlay/overlay.vue
src/overlay/props.ts
src/overlay/type.ts
src/popup/__test__/__snapshots__/demo.test.jsx.snap
src/popup/demos/placement-top.vue

- feat(Overlay): 新增 `customStyle`属性，支持自定义遮罩样式

feat(Overlay): add customStyle attribute

---

src/input/__test__/__snapshots__/index.test.jsx.snap
src/input/__test__/index.test.jsx
src/input/input.vue

test(Input): improve unit test coverage

---

src/textarea/__test__/index.test.jsx
src/textarea/textarea.vue

test(Textarea): improve unit test coverage

---

src/cell/cell.vue

#415 
- fix(Cell): 修复 `RightIcon` 渲染错误

fix(cell): resolve the rendering problem of right icon

---

src/avatar/__test__/__snapshots__/demo.test.jsx.snap
src/avatar/__test__/index.test.jsx
src/avatar/avatar.md
src/avatar/avatar.vue
src/avatar/demos/action.vue
src/avatar/demos/adjust.vue
src/avatar/demos/exhibition.vue
src/avatar/demos/mobile.vue
src/avatar/demos/shape.vue
src/avatar/demos/size.vue
src/avatar/demos/type.vue
src/avatar/props.ts
src/avatar/type.ts
src/cell/__test__/__snapshots__/demo.test.jsx.snap
src/image/image.vue

#378 
- feat(Avatar): 新增 imageProps 属性透传至 Image 组件
- demo(Avatar): 更新示例代码

feat(Avatar): add imageProps attribute

---

src/shared/util.ts
src/skeleton/skeleton.vue
src/upload/upload.vue

chore: remove useless utils

---

src/checkbox/__test__/__snapshots__/demo.test.jsx.snap
src/checkbox/demos/disable.vue
src/checkbox/demos/group.vue
src/checkbox/demos/mobile.vue
src/checkbox/demos/size.vue

- ☑️  文档改进
- ☑️  演示代码改进
#413 
-docs(checkbox): 更新组件 checkbox 示例文档和组件demo, 升级语法糖

docs(checkbox): update docs and demo

---

src/fab/__test__/__snapshots__/demo.test.jsx.snap
src/fab/demos/mobile.vue
src/fab/demos/text.vue

docs(fab): update docs and demo

---

src/dropdown-menu/__test__/__snapshots__/demo.test.jsx.snap
src/dropdown-menu/demos/disabled.vue
src/dropdown-menu/demos/mobile.vue
src/dropdown-menu/demos/multiple.vue
src/dropdown-menu/demos/single.vue
src/dropdown-menu/demos/tree.vue

#413 
- feat(DropdownMenu): 更新示例代码

docs(dropdown-menu): update docs and demo

---

src/swiper/__test__/__snapshots__/index.test.jsx.snap
src/swiper/__test__/index.test.jsx

[tdesign-mobile-vue#271](https://github.com/Tencent/tdesign-mobile-vue/issues/271)
- feat(Swiper): 新增单元测试

test(swiper): add unit test for swiper

---

src/indexes/__test__/index.test.tsx
src/indexes/indexes.vue

test(indexes): 新增`Index` 单元测试用例

---

src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/__test__/demo.test.jsx
src/cascader/demos/mobile.vue
src/cascader/demos/status.vue

re #413 
[示例代码改造](https://github.com/Tencent/tdesign-mobile-vue/issues/413)
- docs(Cascader): 更新示例代码

docs: update cascader demo

---

src/calendar/__test__/__snapshots__/index.test.jsx.snap
src/calendar/__test__/index.test.jsx
src/calendar/calendar.vue

- fix(Calendar): 修复 confirmBtn 属性传递 `string` 类型时渲染错误
- test(Calendar): 新增单元测试

test(Calendar): add unit test for calendar

---

src/overlay/__test__/index.test.jsx

test(Overlay): improve unit test coverage

---

src/message/__test__/index.test.jsx

test(Message): improve unit test coverage

---

src/steps/__test__/__snapshots__/demo.test.jsx.snap
src/steps/demos/click.vue
src/steps/demos/content.vue
src/steps/demos/horizontal.vue
src/steps/demos/icon.vue
src/steps/demos/mobile.vue
src/steps/demos/vertical-readonly.vue
src/steps/demos/vertical.vue

docs(steps): update doc and demo

---

src/list/demos/err-tip.vue
src/list/demos/mobile.vue
src/list/demos/pull-refresh.vue

docs(list): update demo

---

src/list/demos/err-tip.vue
src/list/demos/mobile.vue
src/list/demos/pull-refresh.vue

#413 
-docs(list): 更新组件list示例文档和组件demo, 升级语法糖

docs(list): update docs and demo

---

package.json
src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/steps/__test__/__snapshots__/demo.test.jsx.snap
src/steps/__test__/demo.test.jsx

- test(Steps): 更新示例快照
- test(Cascader):  更新示例快照
- chroe：固定 @vue/runtime-core 版本

chroe: lock @vue/runtime-core version && update snapshot

---

src/back-top/__test__/__snapshots__/demo.test.jsx.snap
src/back-top/__test__/demo.test.jsx
src/back-top/back-top.vue
src/back-top/demos/base.vue
src/back-top/demos/half-round.vue
src/back-top/demos/mobile.vue
src/back-top/demos/round.vue

docs(back-top): update docs and demo 修复半圆样式问题

---

src/count-down/__test__/__snapshots__/demo.test.jsx.snap
src/count-down/demos/base.vue
src/count-down/demos/mobile.vue
src/count-down/demos/specs.vue

re #413
- docs(countdown): 更新countdown示例代码

docs(coutdown): update countdown demo

---

package.json

背景： 官网二维码不显示
方案： 暂时固定 tdesign-site-components 版本为 0.11.5
- chore: lock tdesign-site-components version
、

chore: lock tdesign-site-components version

---

package.json

chore: update site

---

src/date-time-picker/__test__/__snapshots__/index.test.jsx.snap
src/date-time-picker/__test__/index.test.jsx
src/loading/__test__/__snapshots__/index.test.jsx.snap
src/loading/icon/gradient.vue

- fix(Loading): 修复部分浏览器下 loading 晃动问题

fix(Loading): fix loading render in safari

---

CHANGELOG.md

fix: resolve misspell

---

src/components.ts
src/footer/__test__/__snapshots__/demo.test.jsx.snap
src/footer/__test__/demo.test.jsx
src/footer/__test__/index.test.jsx
src/footer/demos/base.vue
src/footer/demos/link.vue
src/footer/demos/logo.vue
src/footer/demos/mobile.vue
src/footer/footer.en-US.md
src/footer/footer.md
src/footer/footer.vue
src/footer/index.ts
src/footer/style/css.js
src/footer/style/index.js
src/footer/type.ts

https://github.com/Tencent/tdesign-mobile-vue/issues/514?target=footer
1.新增组件 footer
2. ![截屏2023-03-21 10 07 31](https://user-images.githubusercontent.com/19382362/226502887-9cb34b91-616b-4908-b4eb-2388e83f076e.png)
- feat(footer): 增加组件 footer

chore(footer): base code

---

src/radio/__test__/index.test.jsx
src/radio/radio.vue

Reverts Tencent/tdesign-mobile-vue#570

Revert "V0.17.0"

---

src/checkbox/checkbox-group.vue
src/checkbox/checkbox.vue

fix: resolve path reference problem

---

src/action-sheet/__test__/__snapshots__/demo.test.jsx.snap
src/calendar/__test__/__snapshots__/demo.test.jsx.snap
src/calendar/__test__/__snapshots__/index.test.jsx.snap
src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap
src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/drawer/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/image-viewer/__test__/__snapshots__/demo.test.jsx.snap
src/overlay/__test__/__snapshots__/demo.test.jsx.snap
src/overlay/__test__/index.test.jsx
src/overlay/demos/base.vue
src/overlay/demos/mobile.vue
src/overlay/overlay.en-US.md
src/overlay/overlay.md
src/overlay/overlay.vue
src/overlay/props.ts
src/overlay/type.ts
src/picker/__test__/__snapshots__/demo.test.jsx.snap
src/popup/__test__/__snapshots__/demo.test.jsx.snap
src/popup/__test__/index.test.jsx
src/toast/demos/overlay.vue

- break(Overlay): 移除 transparent 属性，新增 backgroundColor 属性
- feat(Overlay): 支持 CSS Variables 实现主题定制

refactor(overlay): change api

---

src/checkbox/checkbox.vue
src/form/form.vue
src/notice-bar/demos/customization.vue
src/notice-bar/demos/event.vue
src/picker/demos/cascade.vue
src/pull-down-refresh/demos/timeout.vue

背景：<img width="513" alt="截屏2023-04-19 16 43 09" src="https://user-images.githubusercontent.com/51158141/233019923-0fd60810-fe28-4e4b-9509-8db1e227a10b.png">
原因： rollup 未做别名配置项，
方案：组件内部不在使用别名
- fix(build): 组件内部不在使用别名

fix(Build): no use aliases

---

.eslintignore

feat: update .eslintignore

---

src/tag/tag.vue

#619 
- fix(Tag): 解决 `close` 事件冒泡问题

fix(Tag): resolve bubble

---

.github/workflows/typos-config.toml

fix: update config for typos

---

.husky/prepare-commit-msg

chore: fix husky 异常

---

src/button/button.vue
src/shared/hover.ts

fix(button): resolve hover style

---

src/badge/badge.en-US.md
src/badge/badge.md
src/badge/props.ts
src/badge/type.ts
src/common.ts

无
更新文档
- fix(Badge): 更正属性 shape、size

fix(badge): resolve api

---

src/tab-bar/tab-bar.vue

fix(TabBar): no use aliases

---

src/notice-bar/__test__/__snapshots__/demo.test.jsx.snap
src/notice-bar/__test__/index.test.jsx

test(NoticeBar): update test

---

src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/dialog/__test__/demo.test.jsx
src/list/__test__/__snapshots__/demo.test.jsx.snap
src/pull-down-refresh/__test__/__snapshots__/demo.test.jsx.snap
src/pull-down-refresh/__test__/__snapshots__/index.test.jsx.snap
src/pull-down-refresh/__test__/index.test.jsx
src/pull-down-refresh/demos/base.vue
src/pull-down-refresh/demos/mobile.vue
src/pull-down-refresh/props.ts
src/pull-down-refresh/pull-down-refresh.en-US.md
src/pull-down-refresh/pull-down-refresh.md
src/pull-down-refresh/pull-down-refresh.vue
src/pull-down-refresh/style/index.js
src/pull-down-refresh/type.ts
src/shared/util.ts

fix #625 
common：https://github.com/Tencent/tdesign-common/pull/1317
- break(PullDownRefresh): 调整 DOM 结构，使用新样式
- feat(PullDownRefresh)：新增 scrolltolower 事件
- fix(PullDownRefresh): 修复 value = true 不触发加载态的问题

feat(PullDownRefresh): use new style

---

src/collapse/__test__/__snapshots__/demo.test.jsx.snap
src/collapse/__test__/demo.test.jsx
src/collapse/__test__/index.test.jsx
src/collapse/collapse-panel-props.ts
src/collapse/collapse-panel.vue
src/collapse/collapse.en-US.md
src/collapse/collapse.md
src/collapse/collapse.vue
src/collapse/demos/action.vue
src/collapse/demos/base.vue
src/collapse/demos/card.vue
src/collapse/demos/mobile.vue
src/collapse/demos/placement.vue
src/collapse/props.ts
src/collapse/style/index.js
src/collapse/type.ts

fix #623
重构 Collapse
- break(Collapse): 调整 DOM
- feat(Collapse): 新增 placement、theme 属性

fix(collapse): using new version

---

src/avatar/__test__/index.test.jsx
src/avatar/avatar.vue

fix #627 
- fix(Avatar): 解决控制台告警问题

fix(Avatar): resole console warn

---

src/dialog/demos/plugin.vue

fix(Dialog): resolve demo error

---

src/form/__test__/__snapshots__/demo.test.jsx.snap
src/upload/__test__/__snapshots__/demo.test.jsx.snap
src/upload/__test__/demo.test.jsx
src/upload/demos/custom.vue
src/upload/demos/mobile.vue
src/upload/props.ts
src/upload/type.ts
src/upload/upload.en-US.md
src/upload/upload.md
src/upload/upload.vue

- feat(Upload): 新增 `addContent` 属性
- feat(Upload): 支持 `--td-upload-width` 、 `--td-upload-height`、`--td-upload-background` 变量

feat(Upload): support add-content attr

---

CHANGELOG.md
package.json

chore: publish v0.22.0

---

src/shared/index.ts
src/swipe-cell/swipe-cell.vue
src/swipe-cell/useSureConfirm.ts

fix #688 
组件内部禁止使用别名
- fix(SwipeCell): 修复引用问题

fix(SwipeCell): disallow aliases in components

---

package.json

chore: publish v0.22.0-beta

---

site/docs.config.js
src/components.ts
src/table/__test__/__snapshots__/demo.test.jsx.snap
src/table/__test__/demo.test.jsx
src/table/base-table-props.ts
src/table/base-table.vue
src/table/demos/base.vue
src/table/demos/bordered.vue
src/table/demos/mobile.vue
src/table/demos/scroll.vue
src/table/demos/stripe.vue
src/table/hooks/useClassName.ts
src/table/hooks/useStyle.ts
src/table/index.ts
src/table/interface.ts
src/table/style/css.js
src/table/style/index.js
src/table/table.en-US.md
src/table/table.md
src/table/type.ts
src/table/utils.ts

common: https://github.com/Tencent/tdesign-common/pull/1357
https://github.com/Tencent/tdesign-mobile-vue/assets/51158141/181042e5-1460-44d6-92f8-fc29f194c08b
说明： 目前 table 仅支持到数据展示，自定义内容和固定行列功能后续补充
- feat(table): 新增 table 组件

feat(table): add table

---

src/progress/__test__/__snapshots__/demo.test.jsx.snap
src/progress/__test__/index.test.jsx
src/progress/constants.ts
src/progress/progress.vue

fix #721
common: https://github.com/Tencent/tdesign-common/pull/1359
- other(Progress): 补充测试用例

test(Progress): add test case

---

src/popup/__test__/index.test.jsx
src/popup/popup.vue

- fix(Popup): 解决使用 `closeBtn` 插槽时关闭无效的问题
- test(Popup): 补充测试用例

fix(Popup): resolved closeBtn invalid when using  slot

---

src/search/__test__/index.test.jsx
src/search/search.vue

fix #726 
- fix(Search): 修复 `leftIcon` 插槽无效的问题
- other(Search): 补充测试用例

test(Search): add test case

---

src/textarea/__test__/index.test.jsx

test(Textarea): add test case

---

src/stepper/__test__/index.test.jsx

test(Stepper): add test case

---

src/switch/__test__/index.test.jsx

test(Switch): add test case

---

src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/input/__test__/__snapshots__/demo.test.jsx.snap
src/input/__test__/index.test.jsx
src/input/input.vue

test(Input): add test case

---

src/toast/__test__/index.test.jsx

test(Toast): add test case

---

src/pull-down-refresh/__test__/index.test.jsx

- [x ] 测试用例
- other(PullDownRefresh): 补充测试用例

test(PullDownRefresh): add test case

---

src/tag/__test__/index.test.jsx

test(Tag): add test case

---

src/cascader/style/css.js

- fix(Cascader): 修复构建后组件样式缺失问题

fix(Cascader): resolved missing styles after build

---

src/footer/__test__/index.test.jsx

test(Footer): add test case

---

src/result/__test__/index.test.jsx

test(Result): add test case

---

src/dropdown-menu/__test__/__snapshots__/demo.test.jsx.snap
src/dropdown-menu/demos/slotDemo.vue
src/dropdown-menu/dropdown-item.vue
src/dropdown-menu/dropdown-menu.vue

- fix(DropdownMenu): support keys

fix(DropdownMenu): support keys

---

src/message/__test__/index.test.jsx

https://github.com/Tencent/tdesign-mobile-vue/issues/717
- test(Message): 完善测试用例

test(message): add test cases

---

src/list/list.vue

fix #747 
fix #809 
fix #779 
fix #792 
- fix(List): 修复 `scroll` 事件返回值不正确的问题
- fix(List): 修复 `load-more` 文案不显示的问题
- fix(List): 修复 `loading` 内容不居中的问题

fix(List): resolve scroll value problem

---

src/link/__test__/index.test.jsx

[【Link】测试覆盖率提升 #715](https://github.com/Tencent/tdesign-mobile-vue/issues/715)
- other(Link): 补充测试用例

test: add link test case

---

src/count-down/__test__/index.test.jsx

fix #704
- other(CountDown): 补充测试用例

test(CountDown): add test case

---

src/upload/__test__/index.test.jsx
src/upload/upload.vue

fix #737 
- test(Upload): 补充测试用例

test(upload): add test cases

---

src/loading/__test__/__snapshots__/index.test.jsx.snap
src/loading/__test__/index.test.jsx
src/loading/demos/speed.vue

fix #716 
- other(Loading): 补充测试用例

test(loading): add test cases

---

src/steps/__test__/index.test.jsx

https://github.com/Tencent/tdesign-mobile-vue/issues/729
- test(Staep): 完善测试用例

test(steps): add test cases

---

src/back-top/__test__/index.test.jsx

fix #699
- test(BackTop): 补充测试用例

test(backtop): add test cases

---

src/calendar/__test__/__snapshots__/demo.test.jsx.snap
src/calendar/__test__/__snapshots__/index.test.jsx.snap
src/calendar/template.vue

fix #763 
- fix(Calendar): 修复组件圆角样式错误

fix(Calendar): resolved border-radius style problem

---

src/upload/demos/custom.vue

fix #787
- fix(Upload): 修复国徽上传示例占位图错误

fix(Upload): resolved example image error

---

src/popup/popup.vue

common: https://github.com/Tencent/tdesign-common/pull/1382
- fix(Popup): 修复 `preventScrollThrough` 属性无效的问题

fix(Popup): resolved preventScrollThrough invalid

---

src/list/list.vue

- fix(List): 修复有父级元素时滚动值始终为 0 的问题

fix(List): resolve scroll problem

---

src/overlay/overlay.md
src/popup/__test__/index.test.jsx
src/popup/popup.md
src/popup/popup.vue

fix(Popup): resolved the content cannot be scrolled

---

src/tabs/tabs.vue

fix #816 
- fix(Tabs): 修复纵向 `touch` 也会触发tabs切换的问题 

fix(Tabs): resolve scrollY value problem

---

src/dropdown-menu/context.ts
src/dropdown-menu/demos/single.vue
src/dropdown-menu/dropdown-item.vue
src/dropdown-menu/dropdown-menu.vue

- feat(DropdownMenu): 新增 `menuOpened`、`menuClosed` 事件

feat(DropdownMenu): enrich events

---

src/dropdown-menu/context.ts
src/dropdown-menu/dropdown-item.vue
src/dropdown-menu/dropdown-menu.vue

type TriggerSource = 'overlay' | 'menu' | 'content' | 'confirm';
丰富 menuClosed 事件的触发源
- feat(DropdownMenu):  丰富 `menuClosed` 事件触发源

feat(DropdownMenu): enrich TriggerSource for menuClosed event

---

src/tag/__test__/__snapshots__/demo.test.jsx.snap
src/tag/demos/theme.vue

fix #794 
- fix(Tag): 修复示例文案错误

fix(tag): modify demo text

---

src/result/__test__/__snapshots__/demo.test.jsx.snap
src/result/demos/theme.vue

fix #793 
- fix(Result): 修复示例间距样式

style(result): add result demo spacing

---

src/switch/__test__/__snapshots__/demo.test.jsx.snap
src/switch/switch.vue

fix #785 
- fix(Switch): 修复 `loading` 态背景色错误
- fix(Switch): 修复 `loading` 态仍能点击的问题

fix(Switch): resolved loading state style

---

src/empty/__test__/__snapshots__/demo.test.jsx.snap
src/empty/demos/imageEmpty.vue

fix #788 
- fix(Empty): 移除无效的示例

fix(Empty): remove invalid examples

---

src/dropdown-menu/demos/customized.vue

fix #797 
- fix(DropdownMenu): 修复示例字号及按钮样式错误

fix(DropdownMenu): resolve demo font size

---

src/footer/__test__/__snapshots__/demo.test.jsx.snap
src/footer/demos/link.vue
src/footer/demos/logo.vue

fix #790 
common： https://github.com/Tencent/tdesign-common/pull/1384
- fix(Footer): 更新示例代码

fix(Footer): update demo

---

src/collapse/__test__/index.test.jsx

fix #703 
- other(Collapse): 补充测试用例

test(Collapse): add test cases

---

src/notice-bar/__test__/index.test.jsx

fix #718 
- other(NoticeBar): 补充测试用例

test(NoticeBar): add test cases

---

src/cell/__test__/index.test.jsx

fix #702 
- other(Cell): 补充测试用例

test(Cell): add test cases

---

src/avatar/__test__/index.test.jsx

fix #698 
- other(Avatar): 补充测试用例

test(Avatar): add test cases

---

src/swipe-cell/__test__/index.test.jsx

fix #730 
- other(SwipeCell): 补充测试用例

test(swipe-cell): add test cases

---

src/drawer/__test__/index.test.jsx

fix #707 
- other(Drawer): 补充测试用例

test(Drawer): add test case

---

src/grid/__test__/index.test.jsx

fix #711
- other(Grid): 补充测试用例

test(Grid): add test case

---

src/dropdown-menu/dropdown-item.vue
src/dropdown-menu/dropdown-menu.vue

- fix(DropdownMenu): 修复 `closeOnClickOverlay` 属性无效的问题
- fix(DropdownMenu): 修复 `options` 初始值不能为空
- fix(DropdownMenu): 修复 `expose` 产生的告警问题

fix(DropdownMenu): resolve a few issue

---

src/action-sheet/__test__/__snapshots__/demo.test.jsx.snap
src/action-sheet/action-sheet-grid.vue
src/action-sheet/action-sheet-list.vue
src/action-sheet/demos/grid-multiple.vue
src/grid/__test__/__snapshots__/demo.test.jsx.snap
src/grid/grid-item.vue

common: https://github.com/Tencent/tdesign-common/pull/1394
- break(GridItem): 调整DOM结构
- fix(GridItem): 修复 `Image` 属性不支持 `Function` 类型
- fix(ActionSheet): 修复禁用态背景色错误
- fix(ActionSheet): 修复示例占位图错误

style(ActionSheet): resolved style error

---

src/calendar/__test__/index.test.jsx

fix #700 
- other(Calendar): 补充测试用例

test(Calendar): add test cases

---

src/action-sheet/__test__/__snapshots__/demo.test.jsx.snap
src/action-sheet/action-sheet-grid.vue
src/image-viewer/image-viewer.vue
src/notice-bar/__test__/__snapshots__/demo.test.jsx.snap
src/swiper/__test__/__snapshots__/demo.test.jsx.snap
src/swiper/__test__/__snapshots__/index.test.jsx.snap
src/swiper/__test__/index.test.jsx
src/swiper/demos/base.vue
src/swiper/demos/control.vue
src/swiper/demos/custom.vue
src/swiper/demos/fraction.vue
src/swiper/props.ts
src/swiper/swiper-item.vue
src/swiper/swiper.en-US.md
src/swiper/swiper.md
src/swiper/swiper.vue
src/swiper/type.ts

common： https://github.com/Tencent/tdesign-common/pull/1397
- fix(ImageViewer): 修复图片预览显示不全的问题
- feat(Swiper): `height` 属性支持 `string` 类型

fix(ImageViewer): resolved the incomplete picture preview

---

src/tab-bar/__test__/index.test.jsx

fix #733
提升测试覆盖率
- other(TabBar): 补充测试用例

test(tab-bar): improve test coverage

---

src/grid/__test__/__snapshots__/demo.test.jsx.snap
src/grid/grid-item.vue

fix #791 
common: https://github.com/Tencent/tdesign-common/pull/1403
- fix(Grid): 修复组件上下边距及水平滚动时字号错误

fix(Grid): resolved style error

---

src/loading/__test__/__snapshots__/demo.test.jsx.snap
src/loading/demos/mobile.vue
src/loading/demos/size.vue
src/loading/demos/speed.vue

fix #798 
- fix(Loading): 修复示例样式问题

fix(Loading): resolved style error for demo

---

src/navbar/__test__/__snapshots__/demo.test.jsx.snap
src/navbar/__test__/__snapshots__/index.test.jsx.snap
src/navbar/demos/base.vue
src/navbar/navbar.vue

fix #817
修复布局问题
- break(NavBar): 调整布局方式

fix(navbar): resolve layout problem

---

src/slider/__test__/index.test.jsx
src/slider/slider.vue
src/slider/tool.ts

fix #727
提升测试覆盖率，修复重复触发 change 的问题
- fix(Slider): 修复 change 事件重复触发的问题
- test(Slider): 提升测试覆盖率

test(slider): improve test coverage

---

src/dialog/__test__/index.test.jsx
src/dialog/dialog.vue

fix #706 
- test(Dialog): 补充测试用例

test(Dialog): add test unit

---

src/cascader/__test__/index.test.jsx
src/cascader/cascader.vue

fix #701 
- test(Cascader): 补充测试用例

test(Cascader): add unit test

---

src/form/__test__/__snapshots__/demo.test.jsx.snap
src/textarea/__test__/__snapshots__/demo.test.jsx.snap
src/textarea/demos/card.vue
src/textarea/demos/label.vue
src/textarea/demos/maxcharacter.vue
src/textarea/demos/maxlength.vue
src/textarea/demos/mobile.vue
src/textarea/props.ts
src/textarea/textarea.en-US.md
src/textarea/textarea.md
src/textarea/textarea.vue
src/textarea/type.ts

fix #786 
common: https://github.com/Tencent/tdesign-common/pull/1407
- feat(Textarea): 新增 `layout` 属性
- fix(Textarea): 修复 `label` 标签字号错误

feat(Textarea): support layout attr

---

src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/input/__test__/__snapshots__/demo.test.jsx.snap
src/input/__test__/index.test.jsx
src/input/demos/banner.vue
src/input/demos/base.vue
src/input/demos/bordered.vue
src/input/demos/custom.vue
src/input/demos/special.vue
src/input/demos/suffix.vue
src/input/input.en-US.md
src/input/input.md
src/input/input.vue
src/input/props.ts
src/input/type.ts

fix #784
common： https://github.com/Tencent/tdesign-common/pull/1406
- feat(Input): 新增 borderless 属性
- fix(Input): 修复禁用态输入框文本颜色错误
- fix(Input): 修复垂直布局时 `label` 下边距错误
- fix(Input): 修复示例样式问题

feat(Input): support borderless attr

---

src/tabs/__test__/__snapshots__/index.test.jsx.snap
src/tabs/__test__/index.test.jsx

fix #734 
- other(Tabs): 补充测试用例

test(tabs): add test cases

---

src/form/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/index.test.jsx
src/form/form-item.vue
src/form/form.en-US.md
src/form/form.md
src/form/form.vue
src/form/props.ts
src/form/type.ts

fix #710 
- fix(Form): 修复 `FormRule`  中 `type` 属性无效的问题
- fix(Form): 修复 `expose` 中的 `submit` 和 `reset` 事件报错
- fix(Form): 修复文档 `labelWidth` 属性默认值错误
- other(Form): 补充测试用例

test(Form): add unit test

---

src/table/__test__/__snapshots__/demo.test.jsx.snap
src/table/demos/base.vue
src/table/demos/bordered.vue
src/table/demos/scroll.vue
src/table/demos/stripe.vue

fix #781
common: https://github.com/Tencent/tdesign-common/pull/1408
- fix(Table): 修复边框和字号错误
- other(Table): 更新示例

fix(Table): update demo

---

src/button/button.vue

fix #756
无
- fix(Button): 移除禁用态的点击样式
- feat(Button): 增加幽灵按钮的点击样式

fix(button): add color for ghost button on hover

---

src/image-viewer/__test__/index.test.jsx

fix #712 
- other(ImageViewer): 补充测试用例

test(ImageViewer): add test cases

---

src/side-bar/demos/base.vue
src/side-bar/demos/custom.vue
src/side-bar/demos/with-icon.vue

fix #873 
- fix(SideBar): 修复示例错误

fix(SideBar): resolve SideBar demo bug

---

src/image/__test__/__snapshots__/demo.test.jsx.snap
src/image/demos/base.vue
src/image/demos/mobile.vue
src/image/demos/position.vue
src/image/demos/shape.vue
src/image/demos/status.vue
src/image/image.vue

fix #803 
common: https://github.com/Tencent/tdesign-common/pull/1411
- fix(Image): 修复 `error` 默认值失效
- other(Image): 更新示例代码

fix(Image): resolved props.error default value invalid

---

src/indexes/__test__/index.test.jsx

fix #713 
- other(Indexes): 补充测试用例

test(Indexes): add test cases

---

site/mobile/components/header.vue
site/mobile/components/home.vue
site/mobile/router.ts
src/indexes/demos/mobile.vue
src/side-bar/demos/mobile.vue
src/side-bar/side-bar-item.vue
src/side-bar/side-bar.vue
src/steps/steps.vue

fix #760 
优化示例，在需要切换页面的示例中，正常切换路由，保证后退功能可用

fix: resolve demo go-back problem

---

src/list/__test__/__snapshots__/demo.test.jsx.snap
src/pull-down-refresh/__test__/__snapshots__/demo.test.jsx.snap
src/pull-down-refresh/__test__/__snapshots__/index.test.jsx.snap
src/pull-down-refresh/__test__/index.test.jsx
src/pull-down-refresh/pull-down-refresh.vue
src/shared/util.ts

fix #801 
- fix(PullDownRefresh): 修复下拉刷新加载样式未居中问题

fix(PullDownRefresh): reset loading bar height

---

src/fab/fab.vue

无
使用 setup script 重构
- fix(Fab): 改用 setup 语法糖

refactor(fab): using setup

---

package.json

chore: fix ci test

---

src/avatar/__test__/index.test.jsx
src/link/__test__/index.test.jsx
src/link/link.vue
src/result/__test__/index.test.jsx
src/result/result.vue

fix: resolve some test case error

---

src/textarea/__test__/index.test.jsx
src/textarea/demos/maxcharacter.vue
src/textarea/demos/maxlength.vue
src/textarea/textarea.vue

fix #900 
fix #901 
- fix(Textarea): 修复计数器错误

fix(Textarea): resolved indicator error

---

package.json
site/docs.config.js
src/components.ts
src/image/__test__/__snapshots__/demo.test.jsx.snap
src/popover/__test__/__snapshots__/demo.test.jsx.snap
src/popover/__test__/demo.test.jsx
src/popover/demos/mobile.vue
src/popover/demos/placement.vue
src/popover/demos/theme.vue
src/popover/demos/type.vue
src/popover/index.ts
src/popover/popover.en-US.md
src/popover/popover.md
src/popover/popover.vue
src/popover/props.ts
src/popover/style/css.js
src/popover/style/index.js
src/popover/type.ts
src/popup/props.ts
src/popup/type.ts

- feat(Popover): 新增 Popover 弹出气泡组件

feat(Popover): add popover

---

src/divider/__test__/__snapshots__/demo.test.jsx.snap
src/divider/__test__/index.test.jsx
src/divider/divider.en-US.md
src/divider/divider.md
src/divider/divider.vue
src/divider/props.ts
src/divider/type.ts
src/navbar/__test__/__snapshots__/demo.test.jsx.snap

无
移除非必要结构，移除废弃属性
- break(Divider): 调整 DOM，移除 lineColor 废弃属性

refactor(divider): final version

---

src/date-time-picker/date-time-picker.vue

- fix(DateTimePicker): 修复 `modelValue` 属性无效的问题

fix(DateTimePicker): fix modelValue invalid

---

src/stepper/__test__/index.test.jsx
src/stepper/stepper.vue

fix(Stepper): resolved precision problem

---

src/action-sheet/__test__/__snapshots__/demo.test.jsx.snap
src/avatar/__test__/__snapshots__/demo.test.jsx.snap
src/button/__test__/__snapshots__/demo.test.jsx.snap
src/cell/__test__/__snapshots__/demo.test.jsx.snap
src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/empty/__test__/__snapshots__/demo.test.jsx.snap
src/footer/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/grid/__test__/__snapshots__/demo.test.jsx.snap
src/image/__test__/__snapshots__/demo.test.jsx.snap
src/input/__test__/__snapshots__/demo.test.jsx.snap
src/loading/__test__/__snapshots__/demo.test.jsx.snap
src/loading/__test__/__snapshots__/index.test.jsx.snap
src/loading/__test__/index.test.jsx
src/loading/loading.en-US.md
src/loading/loading.md
src/loading/loading.vue
src/loading/props.ts
src/loading/type.ts
src/navbar/__test__/__snapshots__/demo.test.jsx.snap
src/result/__test__/__snapshots__/demo.test.jsx.snap
src/side-bar/__test__/__snapshots__/demo.test.jsx.snap
src/steps/__test__/__snapshots__/demo.test.jsx.snap
src/switch/__test__/__snapshots__/demo.test.jsx.snap
src/upload/__test__/__snapshots__/demo.test.jsx.snap

API： https://github.com/TDesignOteam/tdesign-api/pull/163
- break(Loading):  移除`progress` 属性
- feat(Loading): `indicator` 属性新增 `Slot / Function`类型，支持自定义指示符

feat(Loading): enrich the supported types of indicator properties

---

package.json
src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/__test__/demo.test.jsx
src/cascader/cascader.vue
src/cascader/demos/lazy.vue
src/cascader/demos/mobile.vue

feat(cascader): lazy demo

---

src/popup/popup.vue

- fix(Popup): 修复 `visible-change` 事件参数错误 

fix(Popup): resolved visible-change event parameter error

---

src/form/form.vue
src/image-viewer/image-viewer.vue
src/indexes/indexes.vue
src/list/pull-refresh.vue
src/overlay/overlay.vue
src/picker/picker.class.ts
src/pull-down-refresh/pull-down-refresh.vue
src/search/search.vue
src/shared/dom.ts
src/swipe-cell/swipe-cell.vue
src/swipe-cell/useSwipe.ts
src/swiper/swiper.vue
src/tabs/tabs.vue

chore: add the common function preventDefault

---

src/overlay/style/index.js

- [] 其他
fix #941
- fix(Overlay): 修复 `backgroundColor` 属性致动画失效问题

fix(Overlay): 修复样式引用路径 

---

src/cascader/__test__/index.test.jsx
src/cascader/cascader.en-US.md
src/cascader/cascader.md
src/cascader/cascader.vue
src/cascader/demos/base.vue
src/cascader/type.ts

- feat(Cascader): `pick` 事件新增 `level` 参数

feat(Cascader): add level parameter to pick event

---

site/mobile/components/home.vue
src/collapse/__test__/__snapshots__/demo.test.jsx.snap
src/collapse/collapse-panel.vue

- fix(CollapsePanel): 修复 `expandIcon` 的值为插槽或函数时无效
- other: 修复组件示例 `home` 页面

fix(Collapse): resolved expand-icon attr of collapse-panel is invalid

---

src/popup/popup.vue
src/toast/__test__/index.test.jsx
src/toast/toast.vue

fix(Popup): update className

---

site/mobile/app.vue
site/styles/mobile/demo.less
site/styles/mobile/index.less
src/fab/demos/mobile.vue
src/image-viewer/demos/mobile.vue

chore: update demo layout

---

src/message/demos/theme.vue

fix(Message): update demo

---

src/message/demos/theme.vue

fix(Message): fix demo

---

src/message/index.ts

fix #960  
- fix(Message): 修复 `Message` 关闭时未销毁节点

fix(Message): destroy node when visible is false

---

package.json

无
使用 vite 开发时，并发请求了所有 icon 的代码，导致卡顿
- fix: 解决使用 vite 开发时并行请求太多的问题

chore: update icons version

---

src/dropdown-menu/dropdown-item.vue

fix #979
- fix(DropdownMenu):  `DropdownItem` 的 `value` 属性支持空字符串

fix(dropdown): support dropdown-item value is empty can be updated

---

src/popup/popup.vue

fix #969 
- fix(Popup): 修复多个 `popup` 时 `preventScrollThrough` 属性无效

fix(Popup): resolved preventScrollThrough invalid when multiple popups

---

src/upload/demos/base.vue
src/upload/props.ts
src/upload/type.ts
src/upload/upload.en-US.md
src/upload/upload.md
src/upload/upload.vue

fix #973 
common: https://github.com/TDesignOteam/tdesign-api/pull/178
- fix(Upload): 修复 `v-model` 无效的问题

feat(Upload): support v-model

---

src/message/index.ts
src/message/message.vue

fix #984 
- fix(Message): 修复函数式调用传入 `context` 时 `ts` 类型报错
- fix(Message): 修复关闭窗体时控制台报错

fix(Message): resolved console error

---

src/cascader/__test__/index.test.jsx
src/cascader/cascader.vue

fix #982 
- fix(Cascader): 修复点选后未勾选的问题

fix(Cascader): resolved selectedValue not update

---

src/upload/__test__/index.test.jsx
src/upload/upload.vue

fix #966 
- fix(Upload): 修复 `onPreview`, `onSuccess`, `onRemove`, `onSelectChange` 无效

fix(upload): resolved some event invalid

---

src/calendar/calendar.vue
src/calendar/template.vue

无
无
- fix(Calendar): 解决属性不支持响应式的问题

fix(calendar): enable reactive for props

---

site/web/app.vue
src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/__test__/__snapshots__/index.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap

chore: support all version for site

---

src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/__test__/__snapshots__/index.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/tag/tag.vue

- fix(Tag): 修复当 `disabled` 为 `true` 时， `closable` 无效的问题

fix(Tag): resolve closable invalid when disabled is true

---

src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/__test__/__snapshots__/index.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/swiper/__test__/__snapshots__/demo.test.jsx.snap
src/swiper/__test__/index.test.jsx
src/swiper/demos/base.vue
src/swiper/demos/card.vue
src/swiper/demos/control.vue
src/swiper/demos/custom.vue
src/swiper/demos/fraction.vue
src/swiper/demos/vertical.vue
src/swiper/swiper.en-US.md
src/swiper/swiper.md
src/swiper/swiper.vue
src/swiper/type.ts

- fix(Swiper): 修复 `change` 事件参数错误

fix(Swiper): resolved change event parameter error

---

src/avatar/avatar.vue
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/stepper/__test__/__snapshots__/demo.test.jsx.snap

- fix(Avatar): 修复 `src` 属性不支持应式的问题

fix(Avatar): resolved src cannot be updated responsively

---

src/badge/badge.vue

无
无
- fix(Badge): 修复 count 不支持 slot 的问题

fix(badge): enable count slot

---

src/dropdown-menu/dropdown-menu.vue

fix #1003 
- fix(DropdownMenu): 修复单选和多选混合使用是 `label` 显示错误问题

fix(DropdownMenu): resolve label bug

---

src/radio/radio.en-US.md
src/radio/radio.md
src/radio/type.ts

fix #1012 
- fix(Radio): 修复 `icon='none'` 时 `ts` 类型报错

fix(Radio): resolved icon attr types error

---

src/slider/slider.vue

fix #1019
- fix(Slider): 修复 `max` 存在时，刻度计算错误

fix(Slider): resolved abnormal calculation of slider mark

---

src/message/index.ts

fix #1027 
- fix(Message): 修复函数式调用时 `onDurationEnd` 属性无效

fix(Message): resolved onDurationEnd invalid when use MessagePlugin

---

src/cell/__test__/__snapshots__/demo.test.jsx.snap
src/cell/cell-group-props.ts
src/cell/cell-group.vue
src/cell/cell.en-US.md
src/cell/cell.md
src/cell/type.ts
src/indexes/__test__/__snapshots__/demo.test.jsx.snap
src/picker/__test__/__snapshots__/demo.test.jsx.snap

common：https://github.com/Tencent/tdesign-common/pull/1556
- break(CellGroup): 调整 `DOM` 结构
- fix(CellGroup): 修复 `bordered` 属性无效
- feat(CellGroup): `CellGroup` 最后一项 `Cell` 无 `border`

fix(CellGroup): resolved bordered invalid

---

src/date-time-picker/date-time-picker.vue

示例
https://stackblitz.com/edit/u5mx16-hr3j5k?file=src%2Fdemo.vue
没有写onConfirm时，控制台报错
onConfirm api文档是非必填。目前没有传onConfirm会报错，增加非空判断
- fix(dateTimePicker):  修复 `onConfirm` 为空时，控制台报错

fix(datetimepicker): onConfirm非必填

---

src/calendar/__test__/__snapshots__/demo.test.jsx.snap
src/calendar/__test__/__snapshots__/index.test.jsx.snap
src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/__test__/__snapshots__/index.test.jsx.snap
src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap
src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/drawer/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/picker/__test__/__snapshots__/demo.test.jsx.snap
src/popup/__test__/__snapshots__/demo.test.jsx.snap
src/popup/popup.vue

This reverts commit a0e016d3b3083e106d027c3f0944133318b7706b.

Revert "fix(t-popup): display影响touch事件，改用visibility (#1057)"

---

src/cell/__test__/__snapshots__/demo.test.jsx.snap
src/cell/cell-group.vue
src/indexes/__test__/__snapshots__/demo.test.jsx.snap
src/picker/__test__/__snapshots__/demo.test.jsx.snap

fix #1066 
- fix(CellGroup): 修复组件层 `class` 属性无效和控制台告警

fix(CellGroup): resolved console warn

---

src/swiper/demos/base.vue
src/swiper/swiper.vue

fix #1056 
- fix(Swiper): 修复 `click` 事件无效的问题

fix(Swiper): resolved click event invalid

---

.github/workflows/auto-release.yml

- other: 修复 `CHANGELOG` 自动生成时缩进格式异常

chore: fix indent

---

src/pull-down-refresh/pull-down-refresh.vue
src/pull-down-refresh/useTouch.ts

fix #1075
fix(pullDownRefresh): 优化与 `SwipeCell` 同用时左滑操作易触发下拉的问题

fix(pull-down-refresh): 修正下拉刷新

---

src/side-bar/side-bar-item.vue

fix #1084
- fix(SideBar): 修复按需引入时控制台告警

fix(SideBar): use relative paths to import

---

src/grid/__test__/__snapshots__/demo.test.jsx.snap
src/grid/grid-item.vue
src/grid/grid.vue

common： https://github.com/Tencent/tdesign-common/pull/1595
fix #1085 
- fix(Grid): 修复 boder 边框缺失

fix(Grid): resolved border style error

---

src/sticky/demos/container.vue

fix(Sticky): resolved bgColor error for demo

---

src/radio/radio-group.vue
src/radio/radio.vue
src/radio/type.ts

- fix(Radio): `allowUncheck` 属性无效

fix(radio): props allow-uncheck invalid

---

src/toast/toast.vue

[#1116 ](https://github.com/Tencent/tdesign-mobile-vue/issues/1116)
- fix(toast): 修正 toast 文字居中展示

fix(toast): toast text center without theme

---

src/swipe-cell/__test__/__snapshots__/demo.test.jsx.snap
src/swipe-cell/swipe-cell.vue

[#1118](https://github.com/Tencent/tdesign-mobile-vue/issues/1118)
- feat(swipe-cell): remove style

feat(swipe-cell): remove style

---

src/popup/demos/base.vue
src/popup/demos/custom-close.vue
src/popup/demos/with-title.vue

style(popup): demo 样式调整

---

src/table/base-table.vue

fix #1131
- fix(table): 修正 table empty 权重问题

fix(table): 修正 table empty 权重问题

---

src/popup/__test__/__snapshots__/demo.test.jsx.snap
src/popup/popup.vue

fix #1126
- fix(Popup): 修复在组件上使用 `class`和`style` 时控制台警告

fix(popup): 修复在组件上使用class属性和style属性,会有vue警告

---

src/collapse/collapse-panel.vue

fix #1134 
- fix(Collapse): 修复在 `Popup` 等窗体组件中使用时渲染错误

fix(collapse): fix getBoundingClientRect

---

src/dropdown-menu/dropdown-menu.vue

复现示例： https://stackblitz.com/edit/8fs4lh?file=src%2Fdemo.vue
排查是dropdown-menu中的icon给定了size="24", 增加的style覆盖了font-size， 去掉icon的size即可
- fix(DropdownMenu):  修复`--td-dropdown-menu-icon-sizem` 变量无效

fix(dropdownmenu): dropdownMenu配置--td-dropdown-menu-icon-sizem不起效

---

src/message/message.vue
src/upload/hooks/useUpload.ts

之前的某个版本里 lodash 引入方式有问题，导致构建时整个 lodash 被引入进去了
- fix: 修正 lodash 引入

fix: 修正 lodash 引入

---

src/input/input.vue

#1153 
在input.vue的props中增加pattern和inputmode的透传，暂时不暴露到文档中
- fix(input): input增加pattern, inputmode的透传

feat(input): input增加pattern, inputmode的透传

---

src/slider/demos/label.vue

官网示例 slider 带数值单游标示例 无法拖动
示例中onChange方法中赋值问题
- fix(Slider): 修复带数值单游标示例无法拖动问题

fix(slider): 带数值单游标示例无法拖动问题

---

src/textarea/demos/card.vue
src/textarea/demos/custom.vue

1. 演示代码传参类型错误
2. 进而导致 Vue Warn
- fix(Textarea): 修复因参数类型错误产生的控制台告警

fix(textarea): demo vue warn and doc

---

src/picker/picker.vue

fix #1155
1. 要解决的具体问题
异步加载的columns时，导致选择异常问题(pickerItemInstanceArray没有实时更新)
2. 列出最终的 API 实现和用法
pickerItemInstanceArray改ref获取，在columns更新时，能实时拿到picker-item的实例（expose内容）
- fix(Picker): 修复`columns` 为异步加载数据时点选报错

fix(picker): 修复异步加载的 columns时，导致选择异常问题

---

src/action-sheet/action-sheet.vue

emit 事件 `update:visible` 未声明
- other(ActionSheet): 处理控制台告警

fix(action-sheet): vue warn

---

src/slider/demos/step.vue
src/slider/slider.vue

fix #1170 
1. slider的step支持小数。#1170
2. 单游标滑块step不生效， 官网示例 带刻度单游标 可复现： https://stackblitz.com/edit/udfkda?file=src%2Fdemo.vue
1. 通过min, max, step的配置计算精度
2. calcByStep中根据精度返回值
3. 单游标滑块增加calcByStep的计算
- fix(Slider): `step` 属性支持小数

feat(slider): slider的step支持小数

---

src/table/__test__/__snapshots__/demo.test.jsx.snap
src/table/demos/scroll.vue

fix #1183 
- fix(Table): 修复演示代码错误

fix(Table): resolved demo error

---

src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/cascader.en-US.md
src/cascader/cascader.md
src/cascader/cascader.vue
src/cascader/demos/check-strictly.vue
src/cascader/demos/mobile.vue
src/cascader/props.ts

#1156
- feat(Cascader):  新增 `checkStrictly`

feat(cascader): cascader支持checkStrictly

---

src/popup/popup.vue

fix #1198 
- fix(Popup): 处理 `t-popup-overflow-hidden` 类名未移除的问题

fix(popup): body lock class name not removed

---

src/table/base-table.vue

fix #1201
- fix(Table): 修复 `colKey` 值取 `serial-number` 时无效的问题

fix(Table): resolved the invalid serial-number

---

src/swipe-cell/swipe-cell.vue

https://github.com/Tencent/tdesign-mobile-vue/issues/1167
- fix(swipe-cell): 修复收回单元格时存在卡顿的问题

fix(swipe-cell): 修复收回单元格时存在卡顿的问题

---

src/calendar/calendar.vue

fix #1222
- fix(Calendar): 修复日历组件title插槽缺失的问题 (#1222)

fix(Calendar): 修复日历组件title插槽缺失的问题 (#1222)

---

src/tabs/tabs.vue

类似 #1084
- fix(Tabs): 修复按需引入时使用Tabs控制台告警

fix(Tabs): use relative paths to import to fix t-badge warn

---

src/message/index.ts

fix #1219
避免使用过程中一定要携带一个特定的 Context，写起来重复啰嗦。
- feat(Message): `MessagePlugin`的 `context` 默认指向 `document.body`

feat(message): add default context to defaultProps

---

src/locale/zh_TW.ts

fix #1250 
- feat(Locale): 新增繁體中文语言包

feat: 新增zn_TW语言包

---

src/locale/ja.ts

fix #1252
- feat(Locale): 新增日语语言包

feat: feat: 新增国际化日语ja

---

src/locale/ru.ts

fix #1249
- feat(Locale): 新增俄语语言包

feat(locale): 国际化新增俄语支持

---

.github/workflows/typos-config.toml
src/locale/it-it.ts

fix #1253
- feat(Locale): 新增意大利语言包

feat(locale): language-it

---

src/tag/__test__/__snapshots__/demo.test.jsx.snap
src/tag/tag.vue

修复tag在key未更新时，内容不会更新
fix #1225
- fix(tag): 修复tag不更新

fix(tag): 修复tag不更新

---

package.json
src/dialog/__test__/index.test.jsx
src/dialog/dialog.vue

- fix(Dialog): 修复 `zIndex` 属性无效的问题

fix(Dialog): resolved zIndex invalid

---

src/swipe-cell/__test__/__snapshots__/demo.test.jsx.snap
src/swipe-cell/useSureConfirm.ts

fix #1245 
- fix(SwipeCell): 修复左滑场景 `click` 事件无效

fix(swipe-cell): right slot event cannot be triggered (#1245)

---

src/tag/__test__/__snapshots__/demo.test.jsx.snap
src/tag/tag.vue

Reverts Tencent/tdesign-mobile-vue#1265
- icon 等属性未支持 Function 类型，暂时 Revert

Revert "fix(tag): 修复tag不更新"

---

src/locale/ar_001.ts

fix #1254 
- feat(Locale): 新增阿拉伯语言包

feat(locale): language-ar

---

src/footer/footer.en-US.md
src/footer/footer.md
src/footer/props.ts
src/footer/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/256

feat(footer): sync api

---

src/result/props.ts
src/result/result.en-US.md
src/result/result.md
src/result/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/262/

docs(result): sync api

---

src/swiper/__test__/index.test.jsx
src/swiper/swiper.vue

fix #1283 
- fix(Swiper): `current` 动态修改异常

fix(swiper): current dynamic modification exception

---

src/result/result.tsx

feat(result): support  config-provider  classPrefix

---

.github/workflows/pr-compressed-size.yml

ci(compressed-size): only run in release version

---

src/calendar/__test__/__snapshots__/demo.test.jsx.snap
src/calendar/__test__/__snapshots__/index.test.jsx.snap
src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/__test__/__snapshots__/index.test.jsx.snap
src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap
src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/drawer/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/overlay/__test__/__snapshots__/demo.test.jsx.snap
src/overlay/__test__/index.test.jsx
src/overlay/index.ts
src/overlay/overlay.en-US.md
src/overlay/overlay.md
src/overlay/overlay.tsx
src/overlay/props.ts
src/overlay/type.ts
src/picker/__test__/__snapshots__/demo.test.jsx.snap
src/popup/__test__/__snapshots__/demo.test.jsx.snap

- feat(Overlay): `sfc` 改 `tsx`

refactor(overlay): sfc to tsx

---

src/side-bar/side-bar-item.vue

fix(SideBar): 修复 `SideBarItem` 项 `value` 值错误

fix(side-bar): 修复 side-bar-item value 错误的问题

---

src/popover/__test__/__snapshots__/demo.test.jsx.snap
src/popover/index.ts
src/popover/popover.en-US.md
src/popover/popover.md
src/popover/popover.tsx

- feat(Popover): `sfc` 改 `tsx`

feat(Popover): sfc changed to tsx

---

src/indexes/indexes.tsx

Uncaught TypeError TypeError: indexesRoot.value?.scrollTo is not a function

fix(indexes): scrollTo is not a function

---

src/cell/cell.tsx

fix(cell): slot "note" invoked outside of the render function

---

src/upload/props.ts
src/upload/type.ts

- fix(upload): fix method options
- [x ] 代码演示已提供或无须提供
- [x ] Changelog 已提供或无须提供

fix(upload): fix method options

---

src/stepper/__test__/index.test.jsx
src/stepper/index.ts
src/stepper/props.ts
src/stepper/stepper.en-US.md
src/stepper/stepper.md
src/stepper/stepper.tsx
src/stepper/type.ts

- feat(Stepper): `sfc` 改 `tsx`

refactor(stepper): sfc to tsx

---

src/dropdown-menu/context.ts
src/dropdown-menu/dropdown-item.tsx
src/dropdown-menu/dropdown-menu.tsx

fix #1346
- feat(DropdownMenu): 支持点击外部区域收起下拉框

fix(dropdown-menu): 修复点击下拉框以外区域下拉框需要收起问题

---

src/side-bar/__test__/__snapshots__/demo.test.jsx.snap
src/side-bar/index.ts
src/side-bar/side-bar-item.tsx
src/side-bar/side-bar.tsx

fix #1354
- feat(SideBar): `sfc` 改 `tsx`

feat: sidebar sfc to tsx

---

src/cascader/cascader.vue

fix: build 报错

---

src/message/__test__/__snapshots__/demo.test.jsx.snap
src/message/__test__/index.test.jsx
src/message/index.ts
src/message/message.tsx

- refactor(Message): `sfc` to `tsx`

refactor(message): sfc to tsx

---

src/message/index.ts

fix(Message): support ssr

---

src/notice-bar/__test__/__snapshots__/demo.test.jsx.snap
src/notice-bar/__test__/index.test.jsx
src/notice-bar/index.ts
src/notice-bar/notice-bar.tsx

fix #1361
- feat(NoticeBar): `sfc` 改 `tsx`

feat: notice-bar sfc to tsx

---

src/toast/demos/theme.vue
src/toast/props.ts
src/toast/toast.en-US.md
src/toast/toast.md
src/toast/toast.tsx
src/toast/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/293
fix #1430 
- feat(Toast): 新增 `className` 属性

feat(Toast): add className props

---

src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/input/__test__/__snapshots__/demo.test.jsx.snap
src/input/demos/special.vue
src/input/input.en-US.md
src/input/input.md
src/input/input.tsx
src/input/props.ts
src/input/type.ts

- feat(Input): 新增`spellCheck` 是否开启拼写检查
- feat(Input): TS类型 `InputValue` 支持 `number`

feat(input): support spellCheck

---

CHANGELOG.md
package.json

chore: publish v1.2.4

---

package.json

https://github.com/Tencent/tdesign-mobile-vue/security/dependabot/3

chore: fix axios security

---

src/list/list.en-US.md
src/list/list.md
src/list/list.tsx
src/list/props.ts
src/list/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/302

docs(List): api sync

---

src/config-provider/__test__/__snapshots__/demo.test.jsx.snap
src/config-provider/config-provider.tsx
src/config-provider/index.ts
src/config-provider/useConfig.ts
src/guide/guide.tsx
src/guide/index.ts

- feat(ConfigProvider): `sfc` 改 `tsx`

feat(ConfigProvider): sfc changed to tsx

---

src/form/__test__/__snapshots__/demo.test.jsx.snap
src/form/demos/horizontal.vue
src/form/demos/vertical.vue
src/form/form-item.tsx
src/form/form.en-US.md
src/form/form.md
src/form/form.tsx

- feat(Form): 支持`scrollToFirstError`，自动滚动到第一个校验不通过的字段位置

feat(Form): support scrollToFirstError

---

src/form/form-item-props.ts
src/form/form.en-US.md
src/form/form.md
src/form/props.ts
src/form/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/309
- docs(Form): `preventSubmitDefault`是否阻止表单提交默认事件
- docs(FormItem): `arrow`是否显示右侧箭头

docs(form): api update

---

src/loading/loading.tsx

chore(Loading): remove alias

---

src/components.ts

背景：
旧`import { Dialog } from 'tdesign-mobile-vue';` 方式引入组件失败，只能`import { DialogPlugin } from 'tdesign-mobile-vue';`。
1.x阶段先兼容旧用法

fix(Dialog): fix import failure

---

.github/CODEOWNERS

chore: add reviewers

---

src/checkbox/index.ts

fix(Checkbox): fix export component name error

---

src/checkbox/checkbox.tsx

fix: remove alias

---

CHANGELOG.md
package.json

chore: publish v1.3.1

---

src/slider/demos/label.vue
src/slider/slider.tsx

需求：支持通过 function 类型，自定义label值
- fix(Slider): 修复 `label` 属性的 `Function` 类型无效

fix(Slider): support function type

---

.husky/prepare-commit-msg

win 系统和CI 环境跳过prepare-commit-msg 

chore: update prepare-commit-msg

---

src/message/message.en-US.md
src/message/message.md
src/message/message.tsx
src/message/props.ts
src/message/type.ts
src/notice-bar/notice-bar.en-US.md
src/notice-bar/notice-bar.md
src/notice-bar/notice-bar.tsx
src/notice-bar/props.ts
src/notice-bar/type.ts

docs:  rename DrawMarquee

---

src/image-viewer/__test__/index.test.jsx
src/image-viewer/image-viewer.tsx

fix #1476
https://github.com/Tencent/tdesign-common/pull/1832
- fix(ImageViewer): 修复页码对齐问题

fix(ImageViewer): keep the icon always occupied

---

src/link/link.en-US.md
src/link/link.md
src/link/link.tsx
src/link/props.ts
src/link/type.ts

fix(Link): disabled priority

---

src/rate/__test__/__snapshots__/demo.test.jsx.snap
src/rate/__test__/index.test.jsx
src/rate/demos/mobile.vue
src/rate/demos/placement.vue
src/rate/props.ts
src/rate/rate.en-US.md
src/rate/rate.md
src/rate/rate.tsx
src/rate/type.ts

- https://github.com/Tencent/tdesign-common/pull/1834
- https://github.com/Tencent/tdesign-common/pull/1837
- https://github.com/TDesignOteam/tdesign-api/pull/333
- feat(Rate): 新增 `placement` 属性， 支持配置评分弹框的位置

feat(Rate): support placement

---

src/cell/cell.tsx
src/shared/hover.ts

fix #1510 
- fix(Cell): 修复禁用 `Hover` 不生效

fix(cell): v-hover disable invalid

---

src/image-viewer/image-viewer.tsx

fix #1515 
- fix(ImageViewer): 优化预加载逻辑

fix(ImageViewer): preloading logical defects

---

src/dialog/index.ts

fix #1477
onClose 事件应该只是隐藏 DOM，而不是移除 DOM
- fix(Dialog): 修复函数式调用 `Dialog` 时关闭按钮不生效

fix(Dialog): during function calls, the close button is not working properly

---

.github/workflows/pr-comment-ci.yml

feat: upgrade pr-comment-ci

---

.github/workflows/pr-comment-ci.yml
CHANGELOG.md
package.json
src/button/button.en-US.md
src/button/button.md
src/button/demos/base.vue
src/button/demos/status.vue
src/button/demos/theme.vue
src/button/props.ts
src/button/type.ts

章节 | from  | to 
-- | -- | -- 
基础 | <img width="429" alt="image" src="https://github.com/user-attachments/assets/d7d47857-f7c5-4177-abe7-18abde7d090c"> | <img width="429" alt="image" src="https://github.com/user-attachments/assets/a531ab4b-74e7-4fae-9710-bacea625b083"> 
禁用 | <img width="396" alt="image" src="https://github.com/user-attachments/assets/676d66fc-f964-49db-8b6c-a369fd5d7ccb"> | <img width="401" alt="image" src="https://github.com/user-attachments/assets/006ce1ae-f27e-4ded-ac6f-ef13ff5a2a21">
主题 | <img width="424" alt="image" src="https://github.com/user-attachments/assets/cf19ae18-9276-40a3-90e4-248e9f73fa45"> | <img width="431" alt="image" src="https://github.com/user-attachments/assets/6d860fd0-ce4e-4bbb-b273-56d8f3c9aaea"> …

feat(Button): 增加虚框按钮演示

---

src/avatar/__test__/__snapshots__/demo.test.jsx.snap
src/badge/__test__/__snapshots__/demo.test.jsx.snap
src/badge/badge.tsx
src/cell/__test__/__snapshots__/demo.test.jsx.snap
src/grid/__test__/__snapshots__/demo.test.jsx.snap
src/side-bar/__test__/__snapshots__/demo.test.jsx.snap
src/tab-bar/__test__/__snapshots__/demo.test.jsx.snap
src/tabs/__test__/__snapshots__/demo.test.jsx.snap

https://github.com/Tencent/tdesign-common/pull/1896
- fix(Badge): 修复 `count` 插槽位置错误，角标改用伪元素实现

fix(Badge): fix count slot position error

---

src/toast/__test__/__snapshots__/demo.test.jsx.snap
src/toast/demos/mobile.vue

- chore(toast): update toast demo text

chore(toast): update toast demo text

---

.eslintrc
package.json
scripts/rollup.config.js
scripts/utils/index.js
scripts/utils/rollup-empty-input.js
src/shared/useTouch/index.ts
src/swipe-cell/useSwipe.ts
tsconfig.json

效果：
- other: 修复 es 包中缺少编译后的样式文件

fix: fix missing style files in es package

---

src/side-bar/side-bar-item.tsx
src/side-bar/side-bar.en-US.md
src/side-bar/side-bar.md
src/side-bar/side-bar.tsx
src/side-bar/type.ts

- https://github.com/TDesignOteam/tdesign-api/pull/391
- chore(SideBarItem): 完善 badgeProps TS 类型

chore(SideBar): fix badgeProps TS type

---

src/collapse/__test__/index.test.jsx
src/collapse/collapse-panel-props.ts
src/collapse/collapse-panel.tsx
src/collapse/collapse.en-US.md
src/collapse/collapse.md
src/collapse/type.ts

- https://github.com/TDesignOteam/tdesign-api/pull/393
- feat(CollapsePanel): 支持`destroyOnCollapse` 配置折叠状态时，是否销毁面板内容

feat(collapse): support destroyOnCollapse

---

src/tab-bar/props.ts
src/tab-bar/tab-bar.en-US.md
src/tab-bar/tab-bar.md
src/tab-bar/type.ts

- https://github.com/TDesignOteam/tdesign-api/pull/392

docs(tab-bar): sync api

---

src/dropdown-menu/dropdown-item-props.ts
src/dropdown-menu/dropdown-menu.en-US.md
src/dropdown-menu/dropdown-menu.md
src/dropdown-menu/type.ts

- https://github.com/TDesignOteam/tdesign-api/pull/398
- docs(DropdownMenu): 文档添加`footer` API

docs(DropdownMenu):  footer api

---

package.json

- fix: 修复`1.4.0` es module 入口文件错误

chore: fix es module

---

src/collapse/collapse-panel.tsx

docs/collapse panel 修复首次为展开状态时，面板高度自适应问题

---

src/checkbox/checkbox.md
src/checkbox/checkbox.tsx
src/checkbox/props.ts
src/checkbox/type.ts

- feat(Checkbox): 支持 `readonly` 只读

feat(checkbox): support readonly

---

src/input/input.en-US.md

- https://github.com/Tencent/tdesign-mobile-vue/issues/1584

fix(input): resolve en docs error

---

src/_util/canUseDom.ts
src/_util/supportsPassive.ts

fix: fix ssr

---

src/badge/__test__/__snapshots__/demo.test.jsx.snap
src/calendar/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cell/__test__/__snapshots__/demo.test.jsx.snap
src/cell/__test__/index.test.jsx
src/cell/cell.tsx
src/collapse/__test__/__snapshots__/demo.test.jsx.snap
src/config-provider/__test__/__snapshots__/demo.test.jsx.snap
src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/indexes/__test__/__snapshots__/demo.test.jsx.snap
src/picker/__test__/__snapshots__/demo.test.jsx.snap
src/side-bar/__test__/__snapshots__/demo.test.jsx.snap
src/swipe-cell/__test__/__snapshots__/demo.test.jsx.snap
src/switch/__test__/__snapshots__/demo.test.jsx.snap

fix #1597 
- dom 对齐小程序端 https://github.com/Tencent/tdesign-miniprogram/blob/673dee2fa5222073273f81ee42b2ce08ef1339cb/src/cell/cell.wxml#L29
- fix(Cell): 修复部分 css vars 无效的问题

fix(Cell): fixed some css var invalid

---

src/slider/slider.tsx

fix #1553 
- fix(Slider): 修复在 `hidden` 元素中组件显示异常

fix(Slider): fix styling errors in hidden element

---

scripts/rollup.config.js

相关pr：
https://github.com/Tencent/tdesign-common/pull/1965
- other: 单独导出涉及 Plugin 相关组件的样式，支持修改类名前缀的部分场景使用

chore: export plugin css file

---

src/image-viewer/image-viewer.tsx

fix #1607
https://github.com/Tencent/tdesign-common/pull/1967
- fix(ImageViewer): 补充图片默认样式

fix(ImageViewer): add image default style

---

src/textarea/textarea.tsx

fix #1613 
- fix(Textarea): 修复指示器不更新问题

fix(Textarea): fix indicator not updating

---

src/style/index.js

fix #1400 
- fix:  修复使用 `import "tdesign-mobile-vue/esm/style/index.js"; ` 引入组件库全局样式资源时，资源路径不存在的问题

chore: remove useless imports

---

package.json

https://www.npmjs.com/package/@vue/server-renderer
vue 从 3.2.13+ 开始，@vue/server-renderer 作为主vue包的依赖项包含在内,不再需要明确安装此包

chore(deps): remove @vue/server-renderer

---

src/form/form-item.tsx
src/input/input.tsx
src/textarea/textarea.tsx

fix #1638 
- fix(Form): 修复失焦时不触发表单校验的问题

fix(form): fix event blur not trigger validate

---

site/web/app.vue

chore: replace version request

---

src/toast/demos/close.vue

fix #1221 
- chore(toast): update toast demo

chore(toast): update toast demo

---

src/upload/__test__/index.test.jsx
src/upload/upload.tsx

pref(upload): adjust code

---

src/popup/popup.md
src/popup/props.ts
src/popup/type.ts

docs(popup): Update description

---

src/radio/props.ts
src/radio/radio-group-props.ts
src/radio/radio.en-US.md
src/radio/radio.md
src/radio/radio.tsx
src/radio/type.ts

API: https://github.com/TDesignOteam/tdesign-api/pull/485
- fix(RadioGroup): 新增 `readonly` 属性

fix(radio): fix placement get value priority

---

src/drawer/demos/icon.vue
src/drawer/drawer.en-US.md
src/drawer/drawer.md
src/drawer/drawer.tsx
src/drawer/props.ts
src/drawer/type.ts

API PR: https://github.com/TDesignOteam/tdesign-api/pull/482
https://github.com/TDesignOteam/tdesign-api/pull/493
- other(Drawer): TS 类型 `TriggerSource` 更名为 `DrawerTriggerSource`

feat(drawer): TS type TriggerSource rename DrawerTriggerSource

---

src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/input/__test__/__snapshots__/demo.test.jsx.snap
src/input/__test__/index.test.jsx
src/input/demos/base.vue
src/input/demos/suffix.vue
src/input/input.tsx

https://github.com/Tencent/tdesign-vue-next/issues/4413
- fix(Input): 修复 `maxlength` 对 `Unicode` 字符计算不准确问题

fix(Input): fix maxlenght property problem

---

src/form/__test__/__snapshots__/demo.test.jsx.snap
src/hooks/useLengthLimit.tsx
src/input/input.tsx
src/textarea/__test__/__snapshots__/demo.test.jsx.snap
src/textarea/textarea.tsx

#1683
- fix(Textarea): 修复 `maxlength` 对 `Unicode` 字符计算不准确问题

fix(Textarea): fix maxlenght property problem

---

site/docs/getting-started.en-US.md
site/docs/getting-started.md

docs: update getting-started

---

src/form/__test__/__snapshots__/demo.test.jsx.snap
src/form/const.ts
src/form/demos/horizontal.vue
src/form/form-item.tsx
src/form/form.tsx

fix #1669
- fix(Form): 补齐 `FormInstanceFunctions`  缺失的 `validateOnly` 事件

fix(Form): fix the invalid validateOnly attr

---

src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/input/__test__/__snapshots__/demo.test.jsx.snap
src/input/input.en-US.md
src/input/input.md
src/input/input.tsx
src/input/props.ts
src/input/type.ts

- feat(Input): 新增 `cursorColor` 属性

feat: feat: 输入框新增 cursorColor 属性，支持自定义光标颜色

---

scripts/test/snap-setup.js
src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap
src/date-time-picker/__test__/__snapshots__/index.test.jsx.snap
src/picker/__test__/__snapshots__/demo.test.jsx.snap

fix: fix pnpm run test:snap-update command execution failure

---

src/action-sheet/action-sheet-grid.tsx
src/action-sheet/action-sheet-list.tsx
src/action-sheet/action-sheet.en-US.md
src/action-sheet/action-sheet.md
src/action-sheet/action-sheet.tsx
src/action-sheet/props.ts
src/action-sheet/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/512

docs(action-sheet): sync api

---

package.json
src/button/__test__/__snapshots__/demo.test.jsx.snap
src/config-provider/__test__/__snapshots__/demo.test.jsx.snap
src/drawer/__test__/__snapshots__/demo.test.jsx.snap
src/dropdown-menu/__test__/__snapshots__/demo.test.jsx.snap
src/fab/__test__/__snapshots__/index.test.jsx.snap
src/input/__test__/__snapshots__/demo.test.jsx.snap
src/navbar/__test__/__snapshots__/index.test.jsx.snap
src/side-bar/__test__/__snapshots__/demo.test.jsx.snap
src/upload/__test__/__snapshots__/demo.test.jsx.snap

https://github.com/Tencent/tdesign-icons/pull/130
- feat(Icon): 新增 `logo-alipay`、`logo-behance-filled` 等图标，修改 `logo-wecom` 图标，移除不合理的 `logo-wecom-filled` 图标

feat(Icon): update version to 0.3.4

---

src/tab-bar/tab-bar-item.tsx

fix #1711
- fix(TabBar): 修复子项数量大于 3 时子项宽度未保持一致

fix(Tabbar): fix style error

---

src/dialog/__test__/__snapshots__/demo.test.jsx.snap
src/dialog/demos/confirm.vue
src/dialog/demos/feedback.vue
src/dialog/demos/image-dialog.vue
src/dialog/demos/mobile.vue
src/dialog/demos/multi-state.vue
src/dialog/dialog.en-US.md
src/dialog/dialog.md
src/dialog/dialog.tsx

fix #1716
https://github.com/Tencent/tdesign-common/pull/2035
- fix(Dialog): 修复圆角样式错误，并新增 `--td-dialog-border-radius`

feat(Dialog): add --td-dialog-border-radius

---

src/popup/popup.en-US.md
src/popup/popup.md
src/popup/popup.tsx

https://github.com/Tencent/tdesign-common/pull/2037
- fix(Popup): 修复圆角错误，并新增 `--td-popup-close-btn-color`

docs(Popup): update docs

---

src/badge/__test__/__snapshots__/demo.test.jsx.snap
src/calendar/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cell/__test__/__snapshots__/demo.test.jsx.snap
src/cell/__test__/index.test.jsx
src/cell/cell.md
src/cell/cell.tsx
src/cell/demos/group.vue
src/cell/demos/multiple.vue
src/cell/demos/single.vue
src/cell/props.ts
src/cell/type.ts
src/collapse/__test__/__snapshots__/demo.test.jsx.snap
src/config-provider/__test__/__snapshots__/demo.test.jsx.snap
src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/indexes/__test__/__snapshots__/demo.test.jsx.snap
src/list/__test__/__snapshots__/index.test.jsx.snap
src/picker/__test__/__snapshots__/demo.test.jsx.snap
src/side-bar/__test__/__snapshots__/demo.test.jsx.snap
src/swipe-cell/__test__/__snapshots__/demo.test.jsx.snap
src/switch/__test__/__snapshots__/demo.test.jsx.snap

https://github.com/TDesignOteam/tdesign-api/pull/529
https://github.com/Tencent/tdesign-common/pull/2034
https://github.com/Tencent/tdesign-common/pull/2036
fix: https://github.com/Tencent/tdesign-mobile-vue/issues/1717
- fix(Cell): 修复部分样式错误，并更新 `align` 属性描述

fix(Cell): fix component style errors

---

.github/workflows/push.yml

PR 会跑两个 CI 做重复的事
如果还需要用到的话，再到 pull-request.yml 补个push 事件

chore: remove push.yml

---

src/tabs/__test__/__snapshots__/demo.test.jsx.snap
src/tabs/demos/icon.vue
src/tabs/props.ts
src/tabs/style/index.js
src/tabs/tab-nav-item.tsx
src/tabs/tab-panel-props.ts
src/tabs/tabs.en-US.md
src/tabs/tabs.md
src/tabs/tabs.tsx
src/tabs/type.ts

- feat(Tabs): 新增 `split` 和 `middle` 属性
- feat(TabPanel): 新增 `icon` 属性

feat(tabs): 新增split/middle属性

---

src/calendar/template.tsx

fix(calendar): resolve maximum recursive updates

---

src/picker/cascade.vue
src/picker/picker-item.tsx
src/picker/picker.en-US.md
src/picker/picker.md
src/picker/picker.tsx
src/picker/props.ts
src/picker/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/551
- feat(Picker):  新增 `keys` 属性

feat(Picker): support keys props

---

src/checkbox/__test__/__snapshots__/demo.test.jsx.snap
src/checkbox/checkbox-group-props.ts
src/checkbox/checkbox.en-US.md
src/checkbox/checkbox.md
src/checkbox/checkbox.tsx
src/checkbox/demos/special.vue
src/checkbox/props.ts
src/checkbox/type.ts

feat(checkbox-group): support borderless props](https://github.com/TDesignOteam/tdesign-api/pull/548)
- feat(CheckboxGroup): 新增 `borderless` 属性

feat(checkbox-group): support borderless props

---

src/fab/demos/advance.vue
src/fab/demos/base.vue
src/fab/fab.en-US.md
src/fab/fab.md
src/fab/fab.tsx
src/fab/props.ts
src/fab/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/547
- feat(Fab): 增强 `draggable` 属性能力，并新增 `yBounds` 属性

feat(fab): support yBounds

---

src/picker/__test__/__snapshots__/demo.test.jsx.snap
src/picker/demos/base.vue
src/picker/picker-item.tsx
src/picker/picker.class.ts
src/picker/picker.tsx
src/picker/type.ts
src/picker/utils.ts

https://github.com/Tencent/tdesign-common/pull/2067
```
// 测试数据
const keys = {
label: 'label.label',
value: 'value.value',
disabled: 'disabled.disabled',
};
const cityOptions = () => {
return [
{
label: { label: '北京市' },
value: { value: '北京市' },
},
{
label: { label: '上海市' },
value: { value: '上海市' },
disabled: { disabled: true },
},
{
label: { label: '广州市' },
value: { value: '广州市' },
},
{
label: { label: '深圳市' },
value: { value: '深圳市' },
},
];
};
```
- feat(Picker): 补充禁用项逻辑

feat(Picker): added disabled state

---

site/docs.config.js

https://github.com/Tencent/tdesign-common/pull/2068
- 补充 自定义主题 文档入口

feat: added custom theme document entry

---

src/picker/picker-item.tsx
src/picker/picker.class.ts

fix #1768
- fix(Picker): 修复 `columns` 为异步数据时，子项无法选中的问题

fix(Picker): fix component exception when columns are asynchronous data

---

.github/workflows/pkg-pr-new.yml
package.json
scripts/rollup.config.js

ci: add pkg.pr.new

---

src/swiper/swiper.tsx

fix #1724 
- fix(Swiper): 修复 `loop` 属性为 `false` 时，首个及最后一个滑动项闪烁的问题

fix(swiper): after closing loop the behavior is not as expected

---

helper/attributes.json
helper/tags.json
helper/web-types.json

chore: update helper

---

src/message/index.ts

fix #1789 
- fix(Message): 修复函数式调用时 `onCloseBtnClick` 属性无效

fix(Message): resolved onCloseBtnClick invalid when use MessagePlugin

---

src/config-provider/config-provider.en-US.md
src/config-provider/config-provider.md
src/config-provider/type.ts

docs(ConfigProvider): update api docs

---

site/web/app.vue
site/web/utils.ts

fix(site): fix version number parsing error

---

src/toast/demos/theme.vue
src/toast/plugin.ts
src/toast/props.ts
src/toast/toast.en-US.md
src/toast/toast.md
src/toast/toast.tsx
src/toast/type.ts

- feat(Toast): 新增 `warning` 主题

feat(toast): add warning theme support

---

.github/workflows/pkg-pr-new.yml
src/button/index.ts
src/dialog/index.ts
src/message/index.ts
src/shared/component.ts
src/toast/plugin.ts

chore: test volar

---

src/pull-down-refresh/pull-down-refresh.tsx
src/pull-down-refresh/useTouch.ts

fix #992
- fix(pullDownRefresh): 修复非顶部下拉出现刷新事件触发的问题

fix(pullDownRefresh): trigger dropdown refresh not at the top

---

.github/workflows/pkg-pr-new.yml

ci(pkg-pr-new): shorter urls

---

src/progress/__test__/__snapshots__/demo.test.jsx.snap
src/progress/constants.ts
src/progress/demos/base.vue
src/progress/demos/mobile.vue
src/progress/progress.en-US.md
src/progress/progress.md
src/progress/progress.tsx
src/progress/props.ts
src/progress/type.ts

fix #599 
https://github.com/TDesignOteam/tdesign-api/pull/606
https://github.com/Tencent/tdesign-common/pull/2112
- feat(Progress): 新增 `size` 属性，仅在环形进度条有效

feat(Progress): support size props

---

src/slider/slider.tsx

fix #1810
- fix(Slider): `marks` 属性不支持 `()=>TNode` 渲染的问题 

fix(slider): marks prop does not support tnode rendering

---

src/navbar/__test__/__snapshots__/demo.test.jsx.snap
src/navbar/__test__/__snapshots__/index.test.jsx.snap
src/navbar/navbar.en-US.md
src/navbar/navbar.md
src/navbar/navbar.tsx
src/navbar/props.ts
src/navbar/type.ts
src/style/index.js
src/tab-bar/props.ts
src/tab-bar/tab-bar.md
src/tab-bar/type.ts

fix #1829 
https://github.com/Tencent/tdesign-common/pull/2128
https://github.com/TDesignOteam/tdesign-api/pull/614
- feat(Navbar): 新增 `safeAreaInsetTop`，是否开启顶部安全区适配

feat(Navbar): support safeAreaInsetTop props

---

src/pull-down-refresh/props.ts
src/pull-down-refresh/pull-down-refresh.en-US.md
src/pull-down-refresh/pull-down-refresh.md
src/pull-down-refresh/pull-down-refresh.tsx
src/pull-down-refresh/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/619
- feat(PullDownRefresh): 新增 `disabled` 属性

feat(PullDownRefresh): add disabled prop

---

CHANGELOG.md
package.json

chore: release 1.8.5

---

src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap
src/date-time-picker/date-time-picker.en-US.md
src/date-time-picker/date-time-picker.md
src/date-time-picker/date-time-picker.tsx
src/date-time-picker/demos/mobile.vue
src/date-time-picker/demos/steps.vue
src/date-time-picker/props.ts
src/date-time-picker/type.ts

fix #1847
- feat(DateTimePicker): 新增 `steps` 属性

feat(date-time-picker): enable steps props

---

src/config-provider/useConfig.ts

- fix(ConfigProvider): 修复全局配置类型提示错误

fix(ConfigProvider): remove type assertions

---

src/dropdown-menu/dropdown-item.tsx
src/popup/popup.en-US.md
src/popup/popup.md
src/popup/popup.tsx
src/popup/props.ts
src/popup/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/533
- feat(Popup): 支持 `duration` 动画时长
- fix(DropdownMenu):  修复自定义 `duration` 无效

feat(popup): support duration

---

src/picker/picker-item.tsx
src/picker/picker.class.ts
src/picker/picker.en-US.md
src/picker/picker.md
src/picker/picker.tsx
src/picker/props.ts
src/picker/type.ts

fix(picker): 修复二次滚动问题

---

src/cascader/__test__/__snapshots__/demo.test.jsx.snap
src/cascader/cascader.en-US.md
src/cascader/cascader.md
src/cascader/cascader.tsx
src/cascader/props.ts
src/cascader/type.ts
src/form/__test__/__snapshots__/demo.test.jsx.snap

- feat(cascader): add middle-content slot

feat(cascader): add middle-content slot

---

src/config-provider/__test__/__snapshots__/demo.test.jsx.snap
src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap
src/date-time-picker/__test__/__snapshots__/index.test.jsx.snap
src/date-time-picker/date-time-picker.en-US.md
src/date-time-picker/date-time-picker.md
src/date-time-picker/date-time-picker.tsx
src/date-time-picker/props.ts
src/date-time-picker/type.ts
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/picker/__test__/__snapshots__/demo.test.jsx.snap
src/picker/picker.en-US.md
src/picker/picker.md
src/picker/picker.tsx
src/picker/props.ts
src/picker/type.ts

- feat(DateTimePicker): 新增 `header` 和 `footer`，用于自定义头部和底部内容

feat(DateTimePicker): 新增 header/footer，用于自定义头部和底部内容

---

src/fab/fab.en-US.md
src/fab/fab.md
src/fab/fab.tsx
src/fab/props.ts
src/fab/type.ts

fix: https://github.com/Tencent/tdesign-mobile-vue/issues/1849
- `Fab`: 扩展 `style` 属性类型，避免警告

fix(fab): 更新style属性类型

---

package.json

- https://github.com/Tencent/tdesign-mobile-vue/issues/1867

chore: fix win run build

---

src/cascader/cascader.tsx
src/cascader/demos/lazy.vue

https://github.com/Tencent/tdesign-mobile-vue/issues/1680
- fix(Cascader): 修复三级懒加载问题

fix(cascader): 修复三级懒加载问题

---

site/vite.config.js

chore: fix toast demo

---

CHANGELOG.md
package.json

chore: publish v1.9.1

---

CHANGELOG.md
changelogs/CHANGELOG-0.x.md

- other(site): 按照统一的、新的日志书写规则标准化日志文档

docs(changelog): standardize according to the new rules

---

src/table/base-table.tsx

chore: fix lint

---

.eslintrc
.github/workflows/pkg-pr-new.yml
src/hooks/useDefaultValue.ts

chore: no-console in packages

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

chore(vscode): expose vscode settings

---

README-zh_CN.md
README.md

docs: add eng readme

---

src/picker/demos/area.vue
src/picker/demos/base.vue
src/picker/demos/customHeight.vue
src/picker/picker-item.tsx
src/picker/picker.en-US.md
src/picker/picker.md
src/picker/type.ts

update type of picker option

---

package.json

chore(des): remove unused @types/jest

---

site/web/plugins/plugin-tdoc/transforms.js
src/footer/__test__/__snapshots__/demo.test.jsx.snap
src/footer/__test__/demo.test.jsx
src/footer/demos/links.vue
src/footer/demos/logo.vue
src/footer/demos/mobile.vue
src/footer/footer.tsx

- feat(Footer): 支持 `logo`，`Links` 与 `text` 同时存在

chore(Footer): allow logo and text to coexist

---

global.d.ts
helper/attributes.json
helper/tags.json
helper/web-types.json

- feat(QRcode): 增加编辑器代码提示，请注意该组件暂时不支持 `unplugin-auto-import` 的使用方式 ⚠️

chore: update code tips

---

src/qrcode/components/style/css.js
src/qrcode/components/style/index.js

fix(QRCode): added component style file entry

---

src/tabs/tabs.tsx

fix #1933
- fix(Tabs): 修复二次滑动问题

fix(tabs): fix double swipe issue for tabs

---

site/docs/getting-started.en-US.md
site/docs/getting-started.md

- other(docs): 通过 `unplugin` 插件按需引入请改为 `import { TDesignResolver } from ' @tdesign-vue-next/auto-import-resolver';`

docs: update TDesignResolver

---

src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap
src/date-time-picker/__test__/demo.test.jsx
src/qrcode/__test__/__snapshots__/demo.test.jsx.snap
src/qrcode/__test__/demo.test.jsx
src/qrcode/demos/base.vue
src/qrcode/demos/bg-color.vue
src/qrcode/demos/borderless.vue
src/qrcode/demos/color.vue
src/qrcode/demos/icon.vue
src/qrcode/demos/level.vue
src/qrcode/demos/mobile.vue
src/qrcode/demos/size.vue
src/qrcode/demos/status.vue

chore(QRCode): improve demos

---

src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap
src/tabs/__test__/__snapshots__/demo.test.jsx.snap
src/tabs/__test__/index.test.jsx
src/tabs/tabs.tsx

feat(tabs): hide track line when initting

---

CHANGELOG.md
package.json

chore: publish v1.10.1

---

src/action-sheet/demos/align.vue
src/action-sheet/demos/grid-multiple.vue
src/action-sheet/demos/grid.vue
src/action-sheet/demos/status.vue
src/back-top/demos/base.vue
src/drawer/demos/icon.vue
src/form/__test__/__snapshots__/demo.test.jsx.snap
src/form/demos/horizontal.vue
src/form/demos/vertical.vue
src/side-bar/demos/base.vue
src/side-bar/demos/custom.vue
src/side-bar/demos/switch.vue
src/side-bar/demos/with-icon.vue
src/slider/demos/vertical.vue
src/swiper/demos/outside.vue
src/table/demos/base.vue
src/table/demos/bordered.vue
src/table/demos/scroll.vue
src/table/demos/stripe.vue
src/toast/demos/close.vue
src/upload/demos/multiple.vue

chore: update console.log in demo

---

src/skeleton/skeleton.en-US.md
src/skeleton/skeleton.md
src/skeleton/type.ts

docs(skeleton): update doc

---

scripts/generate-css-vars.js
src/image-viewer/image-viewer.en-US.md
src/image-viewer/image-viewer.md
src/overlay/overlay.en-US.md
src/overlay/overlay.md
src/toast/toast.en-US.md
src/toast/toast.md

https://github.com/Tencent/tdesign-common/pull/2245
- fix(ImageViwer): 修复背景色错误，导航背景色固定为 `#000`，遮罩背景色使用 `@mask-active`

fix(ImageViewer): fixed background color error

---

src/form/__test__/__snapshots__/demo.test.jsx.snap
src/textarea/__test__/__snapshots__/demo.test.jsx.snap
src/textarea/textarea.tsx

https://github.com/Tencent/tdesign-common/pull/2258
- fix(Textarea): 修复 `--td-textarea-placeholder-color` 无效

fix(Textarea): --td-textarea-placeholder-color is invalid

---

package.json
site/web/main.ts

chore: @tdesign/site-components instead of tdesign-site-components

---

README-zh_CN.md
README.md

chore: update group code path

---

package.json
site/.env.preview
site/web/plugins/changelog-to-json/index.js
site/web/plugins/plugin-tdoc/md-to-vue.js

docs(preview-site): support viewing component logs

---

site/.env.preview
site/web/plugins/changelog-to-json/index.js
site/web/plugins/plugin-tdoc/md-to-vue.js

fix: pr site mobile preview

---

src/cascader/cascader.en-US.md
src/cascader/cascader.md
src/cascader/cascader.tsx
src/cascader/props.ts
src/cascader/type.ts

https://github.com/TDesignOteam/tdesign-api/pull/722
fix #2011
fix #2012
fix #1932
fix #1916
- fix(Cascader): 修复异步加载数据问题
- feat(Cascader): 支持透传 `overlayProps`

fix(cascader): fix lazyload options

---

package.json

chore: publish v1.11.0-beta
