Tencent/tdesign-mobile-vue

src/common.ts, src/indexes/demos/mobile.vue, src/indexes/indexes-anchor.vue, src/indexes/indexes.md, src/indexes/indexes.vue, src/indexes/props.ts, src/indexes/type.ts, test/ssr/__snapshots__/ssr.test.js.snap
- fix(indexes): 增加 indexes 组件的sticky属性
=> feat(indexes): 增加 indexes 组件的sticky属性

src/progress/progress.md, src/progress/props.ts, src/progress/type.ts
https://github.com/Tencent/tdesign-mobile-vue/issues/175
方案：鉴于[小程序端](https://tdesign.tencent.com/miniprogram/components/progress?tab=api)目前也未实现 size 、theme 属性，将文档中size 、theme 相关内容移进行移除。
- refactor(progress): 移除 `theme` 和 `size` 未实现的属性
=> docs(progress): remove size and theme related content

src/swiper/swiper.vue
#171 
- fix(swiper): navigation导航器支持配置minShowNum
=> fix(swiper): navigation support minShowNum

src/checkbox/checkbox.vue, src/checkbox/demos/base.vue, src/checkbox/demos/disable.vue, src/checkbox/demos/group.vue, src/checkbox/demos/icon.vue, src/checkbox/demos/indeterminate.vue, src/checkbox/demos/max.vue, src/checkbox/demos/mobile.vue, src/checkbox/demos/right.vue, src/checkbox/demos/size.vue, test/ssr/__snapshots__/ssr.test.js.snap, test/unit/checkbox/__snapshots__/props.test.js.snap
- fix(checkbox):  support maxContentRow、maxLabelRow
- fix(checkbox-group): support max
=> fix(checkbox):support max、maxContentRow、maxLabelRow

src/dropdown-menu/dropdown-item.vue
无
Radio 和 CheckBox 在 DropdownMenu 下的展示样式有误。
- fix(dropdown-menu): 修复内置的 radio 和 checkbox 样式
=> fix(dropdown-menu): resolve radio style

src/overlay/overlay.vue, src/toast/demos/mobile.vue, src/toast/props.ts, src/toast/toast.md, src/toast/toast.vue, src/toast/type.ts
#176 
补充 Toast overlayProps、showOverlay 属性
- feat(Toast): 补充 overlayProps 支持透传 overlay 属性，支持 showOverlay 遮罩
=> feat(Toast): 补充 Toast overlayProps、showOverlay 属性

src/dialog/demos/confirm.vue, src/dialog/demos/feedback.vue, src/dialog/demos/input.vue, src/dialog/dialog.md
https://github.com/Tencent/tdesign-mobile-vue/issues/279
1. 解决dialog示例代码运行时，无法显示弹窗的问题
2. 将文档示例代码和正常运行的右侧移动端源代码保持一致，即v-model改为v-model:visible
暂不支持v-model语法糖，需要改为v-model:visible
- fix(dialog): 解决dialog示例代码运行时，无法显示弹窗的问题
=> fix(dialog): 修复示例代码运行问题

src/slider/__test__/__snapshots__/demo.test.jsx.snap, src/slider/slider.vue
#277 
- fix(Slider): 修复滑块滑到最左侧时，左侧文本被遮挡
=> fix:  修复滑块滑到最左侧时，遮挡左侧最小值文本

src/drawer/drawer.md, src/drawer/drawer.vue, src/drawer/props.ts, src/popup/popup.md, src/popup/popup.vue, src/popup/props.ts
https://github.com/Tencent/tdesign-mobile-vue/issues/266
新增属性：点击遮罩层是否触发关闭事件
新增closeOnOverlayClick属性：点击遮罩层是否触发关闭事件
=> feat: 针对popup、drawer增加点击遮罩层是否触发关闭事件的配置

src/count-down/__test__/index.test.jsx, src/count-down/count-down.vue, src/shared/useCountDown/index.ts, src/shared/useCountDown/utils.ts
fix #312
[毫秒级渲染配置无效](https://github.com/Tencent/tdesign-mobile-vue/issues/312)
props传入milisecond为true无效
- fix(CountDown): 修复 milisecond 配置无效的问题
- feat(CountDown): 新增单元测试
=> fix(countdown): fix milisecond problem and add unit test

src/swipe-cell/__test__/__snapshots__/demo.test.jsx.snap, src/swipe-cell/__test__/index.test.jsx, src/swipe-cell/swipe-cell.vue
=> test: add unit test for swipe-cell

src/picker/__test__/index.test.jsx, src/picker/picker-item.vue, src/picker/picker.class.ts, src/picker/picker.md, src/picker/picker.vue
增加组件 Picker 的测试用例：
同时发现并修复了一些问题：
1.  默认的确定按钮文案，picker.vue 里是“确定”，picker.md 和 props.ts 是“确认”，目前实际生效的是 **确认**，所以删除 picker.vue 里的默认值（取消按钮文案同理）。
2. picker.md 里 `renderLabel` 类型错误，写的是 `Srting | Function`，但是实际只支持函数，所以修改为仅 `Function` 类型。
3. picker.vue 的 setup 中，`curValueArray` 在定义前使用(ESLint 未拦截这种问题吗？），所以调换了顺序。
还发现了一些问题，tdesign 团队可以后续跟进并修复：
- [test(picker): 增加 picker 组件测试用例](https://github.com/Tencent/tdesign-mobile-vue/commit/ca6ce529884eb23551dbeccc882b75035da4c83f)
- [fix(picker): 修复 ESLint 和类型错误](https://github.com/Tencent/tdesign-mobile-vue/commit/57caf494a2e5c18d7344c14796e17862cc4b0676)
=> test: add unit test for picker

src/button/__test__/__snapshots__/index.test.jsx.snap, src/button/__test__/index.test.jsx
=> test(Button): improve unit test coverage

src/rate/__test__/index.test.jsx, src/rate/rate.vue
- fix(Rate): 修复 ts 类型错误
- test(Rate): 提升组件单元测试覆盖率
=> test(Rate): improve unit test coverage

src/image/__test__/__snapshots__/index.test.jsx.snap, src/image/__test__/index.test.jsx, src/image/__test__/utils.ts, src/image/image.vue
=> test(Image): improve unit test coverage

src/search/__test__/__snapshots__/demo.test.jsx.snap, src/search/__test__/index.test.jsx, src/search/demos/mobile.vue, src/search/search.vue
- fix(Search): 修复 `shape` 属性无效的问题
- fix(Search): 修复 `clear` 事件无效的问题
- feat(Search): 新增组件单元测试
=> test(Search): add unit test for search

src/toast/__test__/__snapshots__/demo.test.jsx.snap, src/toast/__test__/demo.test.jsx, src/toast/demos/icon.vue, src/toast/demos/iconText.vue, src/toast/demos/mask.vue, src/toast/demos/mobile.vue, src/toast/demos/overlay.vue, src/toast/demos/position.vue, src/toast/demos/preventScrollThrough.vue, src/toast/demos/text.vue
=> docs(Toast): update Toast sample code

src/sticky/__test__/__snapshots__/demo.test.jsx.snap, src/sticky/__test__/demo.test.jsx, src/sticky/demos/base.vue, src/sticky/demos/container.vue, src/sticky/demos/mobile.vue, src/sticky/demos/offsetTop.vue
=> docs(sticky): update docs and demo

src/notice-bar/__test__/__snapshots__/demo.test.jsx.snap, src/notice-bar/demos/base.vue, src/notice-bar/demos/icon.vue, src/notice-bar/demos/scrolling.vue, src/notice-bar/demos/theme.vue
- docs(notice-bar): 规范 `NoticeBar` 组件的示例代码
=> docs(notice-bar): 规范 `NoticeBar` 组件的示例代码

src/collapse/__test__/__snapshots__/demo.test.jsx.snap, src/collapse/demos/accordion.vue, src/collapse/demos/action.vue, src/collapse/demos/mobile.vue
#413 
-docs(collapse): 更新组件collapse 示例文档和组件demo, 升级语法糖
=> docs(collapse): update doc and demo

src/swipe-cell/__test__/__snapshots__/demo.test.jsx.snap, src/swipe-cell/demos/bind.vue, src/swipe-cell/demos/btns.vue, src/swipe-cell/demos/content.vue, src/swipe-cell/demos/disabled.vue, src/swipe-cell/demos/event.vue, src/swipe-cell/demos/left-card.vue, src/swipe-cell/demos/left-more-menu.vue, src/swipe-cell/demos/left-one-menu.vue, src/swipe-cell/demos/left-two-menu.vue, src/swipe-cell/demos/mobile.vue, src/swipe-cell/demos/right-menu.vue
https://github.com/Tencent/tdesign-mobile-vue/issues/413
- docs(SwipeCell): 更新示例代码
=> docs(swipe-cell): update docs and demo

src/loading/__test__/__snapshots__/demo.test.jsx.snap, src/loading/__test__/demo.test.jsx, src/loading/demos/bar.vue, src/loading/demos/delay.vue, src/loading/demos/horz.vue, src/loading/demos/mobile.vue, src/loading/demos/pure-text.vue, src/loading/demos/size.vue, src/loading/demos/speed.vue, src/loading/demos/vert.vue
=> docs(Loading): update demo #476

CHANGELOG.md, package.json
=> chore: publish v0.17.0

src/grid/__test__/__snapshots__/demo.test.jsx.snap, src/grid/__test__/demo.test.jsx, src/message/__test__/__snapshots__/demo.test.jsx.snap, src/message/__test__/index.test.jsx, src/message/demos/base.vue, src/message/demos/mobile.vue, src/message/demos/theme.vue, src/message/index.ts, src/message/message.en-US.md, src/message/message.md, src/message/message.vue, src/message/props.ts, src/message/style/index.js, src/message/type.ts
re #548
相关pr：
common：https://github.com/Tencent/tdesign-common/pull/1267
- refactor(message): 调整滚动类型通知的动画初始值，优化动画循环方法
- feat(message): 完善部分单元测试
=> refactor(message): new message

src/cell/cell.vue, src/cell/demos/single.vue, src/shared/hover.ts, src/shared/index.ts
fix #592
新增实现点击效果的 directive
- fix(Cell): 修复 hover 不生效的问题
=> feat: add directive for hover

src/shared/render.ts
[#629](https://github.com/Tencent/tdesign-mobile-vue/issues/629)
在template模式执行其生成的sfc_render时，若有h函数的执行，则其生成的节点会往currentBlock里push，导致dynamicChildren的数量可能出现不一致，最终导致渲染异常或报错
参考源码slot的处理方式，在propsNode是方法时，先使用setBlockTracking(-1)关掉currentBlock的收集，再执行完propsNode方法后，再调用setBlockTracking(1)还原
- fix: extra vnode in dynamicChildren ([issue #629](https://github.com/Tencent/tdesign-mobile-vue/issues/629))
=> fix: extra vnode in dynamicChildren

src/popup/popup.en-US.md, src/popup/popup.md, src/popup/popup.vue, src/popup/props.ts, src/popup/type.ts
无
- feat(Popup): 新增 destroyOnClose 属性
=> fix(popup): add destroy-on-close property

package.json, src/components.ts, src/icon/demos/enhanced.vue, src/icon/demos/mobile.vue, src/icon/icon-svg-props.ts, src/icon/icon.en-US.md, src/icon/icon.md, src/icon/iconfont-props.ts, src/icon/index.ts, src/icon/type.ts, src/shared/component.ts
fix #652 
- feat(Icon): 支持直接通过 `t-icon` 来使用
=> feat(Icon): support TIcon

scripts/rollup.config.js, site/docs/getting-started.md, site/mobile/main.ts
common： [#1392](https://github.com/Tencent/tdesign-common/pull/1392)
背景：按官网说明接入tdesign-mobile-vue，部分组件出现样式问题（Search\DateTimePicker等）。
原因：缺少 _reset.css文件
方案：将_reset.css 涉及的组件样式，全部迁移至组件本身。同时，单独导出 reset.css 到 dist 目录，支持从  `tdesign-mobile-vue/dist/reset.css` 中单独引入，存在不兼容更新。
- break: 默认移除全局 `reset.css` 样式引入，可从 `tdesign-mobile-vue/dist/reset.css` 中单独引入
=> build: export reset.css to the dist directory

src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap, src/date-time-picker/__test__/__snapshots__/index.test.jsx.snap, src/date-time-picker/date-time-picker.vue, src/date-time-picker/style/index.js, src/form/__test__/__snapshots__/demo.test.jsx.snap, src/picker/__test__/__snapshots__/demo.test.jsx.snap, src/picker/__test__/index.test.jsx, src/picker/picker.class.ts
fix #767 
fix #766
背景：时间选择器初始值不能为空的问题，官网Form组件可复现。
- break(DateTimePicker): 调整DOM结构
- fix(DateTimePicker): 修复初始值不能为空的问题
- fix(DateTimePicker): 修复选中文本和弹窗面板圆角样式错误
- fix(Picker): 修复选中文本样式错误
=> fix(DateTimePicker): resolved the initial value cannot be empty

src/form/__test__/__snapshots__/demo.test.jsx.snap, src/form/demos/horizontal.vue, src/form/demos/mobile.vue, src/form/demos/vertical.vue, src/rate/__test__/__snapshots__/demo.test.jsx.snap, src/rate/demos/mobile.vue, src/rate/rate.vue
fix #783 
common: https://github.com/Tencent/tdesign-common/pull/1412
- feat(Rate): 增加组件禁用态样式
- other(Form): 更新示例代码
=> fix(Form): update demo

src/search/__test__/__snapshots__/demo.test.jsx.snap, src/search/__test__/index.test.jsx, src/search/demos/mobile.vue, src/search/search.vue
fix #776 
- fix(Search): 修复 `action-click` 事件无效
=> fix(Search): resolved action-click event invalid

src/popover/demos/placement.vue, src/popover/demos/theme.vue, src/popover/demos/type.vue, src/popover/popover.en-US.md, src/popover/popover.md, src/popover/popover.vue, src/popover/props.ts, src/popover/type.ts
API: https://github.com/TDesignOteam/tdesign-api/pull/162
- feat(Popover): 新增 `closeOnClickOutside` 属性
=> feat(Popover): support close-on-click-outside attr

src/table/base-table.vue
(Table) 修复组件卸载时，异常
fix #924
fix(Table): 修复table组件卸载时，异常报错
=> fix(Table): 修复table组件卸载时，异常报错

src/toast/__test__/index.test.jsx, src/toast/toast.vue
fix #919
fix(toast): 修复preventScrollThrough属性无效
=> fix(toast): 修复preventScrollThrough属性无效

src/tabs/__test__/__snapshots__/demo.test.jsx.snap, src/tabs/props.ts, src/tabs/tabs.en-US.md, src/tabs/tabs.md, src/tabs/tabs.vue, src/tabs/type.ts
背景： 激活条宽度随文本宽度变化
- feat(Tabs): 新增 `bottomLineMode` 属性
- fix(Tabs): 修复 `badgeProps` 属性失效
=> feat(Tabs): add bottomLineMode props

src/form/__test__/__snapshots__/demo.test.jsx.snap, src/textarea/__test__/__snapshots__/demo.test.jsx.snap, src/textarea/props.ts, src/textarea/textarea.vue, src/textarea/type.ts
fix #975 
fix #976 
- break(Textarea): `maxLength`属性默认值变更为 `-1`
- fix(Textarea): 修复 `maxLength`属性无效的问题
=> fix(Textarea): resolved maxlength invalid

src/collapse/__test__/__snapshots__/demo.test.jsx.snap, src/collapse/collapse-panel-props.ts, src/collapse/collapse-panel.vue, src/collapse/collapse.en-US.md, src/collapse/collapse.md, src/collapse/type.ts, src/common.ts
无
无
- feat(CollapsePanel): 新增 `headerLeftIcon` 属性
=> feat(collapse): support header-left-icon

src/drawer/demos/plugin.vue, src/drawer/index.ts, src/drawer/plugin.ts, src/drawer/type.ts, src/plugins.ts
fix #1022 
- fix(Drawer): 修复按需引入时无法在 `SFC` 中使用 `Drawer` 组件
=> fix(Drawer): export drawer component

src/calendar/__test__/__snapshots__/demo.test.jsx.snap, src/calendar/__test__/__snapshots__/index.test.jsx.snap, src/cascader/__test__/__snapshots__/demo.test.jsx.snap, src/cascader/__test__/__snapshots__/index.test.jsx.snap, src/date-time-picker/__test__/__snapshots__/demo.test.jsx.snap, src/dialog/__test__/__snapshots__/demo.test.jsx.snap, src/drawer/__test__/__snapshots__/demo.test.jsx.snap, src/form/__test__/__snapshots__/demo.test.jsx.snap, src/picker/__test__/__snapshots__/demo.test.jsx.snap, src/popup/__test__/__snapshots__/demo.test.jsx.snap, src/popup/popup.vue
v-show
fix #1055 
t-swipe-cell 在 t-popup 中无法左右滑动
经过测试，当t-popup默认显示则不存在这个问题，t-popup使用`v-show`控制元素显示/隐藏，当默认不显示即display为none，绑定的touch事件会存在问题，使用`v-if`也能解决这个问题，既然原本使用`v-show`，那这里我认为 `visibility` 更佳
- fix(Popup): 修复 `TSwipeCell` 在 `TPopup` 中无法左右滑动的问题
=> fix(t-popup): display影响touch事件，改用visibility

src/swiper/swiper-item.vue
fix #1062
该功能在1.0.1版本，1.0.2对比1.0.1代码，应该是swiper组件去掉了这种情况的判断
- fix(ImageViewer): 修复单图时预览错误
=> fix(imageviewer): 只有一张图片时展示错误

src/swiper/demos/custom.vue
官网示例无法显示
排查是示例代码中height="192",  number应该是:height='192', string应该是height='192px'
- fix(Swiper): 修复条状（dots-bar)示例中高度错误问题
=> fix(swiper): dots-bar示例height设置问题

src/picker/picker.vue
fix #1068 
- fix(Picker): 修复 `v-model/modelValue` 为空时组件报错
=> fix(Picker): modelValue is optional

src/shared/hover.ts
fix #1076 
- other: 修复 `v-hover` 产生的控制台告警
=> fix: set passive to true to eliminate the warning of Chrome

src/tabs/tabs.vue
fix #1089
- fix(Cascader): 修复选项卡模式中选中值不更新的问题
=> fix: cascader 选项卡模式选中值不更新问题

src/calendar/calendar.vue, src/calendar/template.vue
fix #1043 
背景： 由于日历展示区域是一个带滚动条的列表，默认滚动条在顶部，当用户传入的value不在日历的起始月份时，需要滚动才能找到设置的目标日期
方案：点开popup或日历加载时，手动将滚动条定位到value所属的月份
- feat(Calendar): 日历选择器支持自动定位到选中日期
=> fix(Calendar): selected date not in view (#1043)

src/common.ts, src/textarea/props.ts, src/textarea/textarea.en-US.md, src/textarea/textarea.md, src/textarea/textarea.vue, src/textarea/type.ts
common： https://github.com/Tencent/tdesign-common/pull/1598/files
API：https://github.com/TDesignOteam/tdesign-api/pull/192
fix #1098 
- fix(Textarea):  新增 `readonly` 属性
=> feat(Textarea): support readonly

src/cascader/cascader.vue, src/shared/useVModel/index.ts
fix #1086 
- fix(Cascader): 修复 `change` 事件被触发两次和 `v-model` 没有响应式的问题
- [] 本条 PR 不需要纳入 Changelog
=> fix(Cascader): 修复 `change` 事件被触发两次和 `v-model` 没有响应式的问题

src/form/__test__/__snapshots__/demo.test.jsx.snap, src/shared/util.ts, src/stepper/__test__/__snapshots__/demo.test.jsx.snap, src/stepper/__test__/index.test.jsx, src/stepper/demos/base.vue, src/stepper/props.ts, src/stepper/stepper.en-US.md, src/stepper/stepper.md, src/stepper/stepper.vue, src/stepper/type.ts
https://github.com/Tencent/tdesign-mobile-vue/issues/1111
- fix(stepper): 新增 `integer` 属性，并修复组件不支持输入小数的问题
=> fix(stepper): stepper输入小数

src/dropdown-menu/dropdown-menu.vue
fix #1119 
主要解决：
1. 多选时，通过label来控制标题不起效问题。
2. 单选时，v-model和defaultValue 初始化时没有标题的问题
复现示例： https://stackblitz.com/edit/m5k9ia-xxbvmk?file=src%2Fdemo.vue
- fix(dropdownMenu): 改变label控制标题不起效问题
=> fix(dropdownmenu): 改变label定义标题不起效

src/popover/__test__/__snapshots__/demo.test.jsx.snap, src/popover/popover.vue
fix #1127 
1. popover首次弹窗被遮挡： updatePopper 增加 currentVisible的判断
2. 箭头优化：
使用popperjs的arrow配置，由popperjs来处理arrow位置： https://popper.js.org/docs/v2/modifiers/arrow/
popperjs的arrow，默认是居中显示， 所以在配置top/left/right/bottom, 直接使用popperjs默认的配置。文本较长时，箭头是居中显示：
其他方向使用padding配置偏移。
right-top/right-bottom/left-top/left-bottom，纵向偏移配置top和bottom, 是相对popper高度偏移
top-left/top-right/bottom-left/bottom-right，横向偏移配置left和right, 是相对popper宽度偏移， 同时考虑超过空间的情况
- fix(Popover): 修复气泡首次弹出被遮挡的问题以及优化箭头
=> fix(popover): popover首次弹窗被遮挡和箭头优化

src/cascader/__test__/__snapshots__/demo.test.jsx.snap, src/cascader/__test__/__snapshots__/index.test.jsx.snap, src/cascader/__test__/index.test.jsx, src/cascader/cascader.en-US.md, src/cascader/cascader.md, src/cascader/cascader.vue, src/cascader/props.ts, src/cascader/type.ts, src/form/__test__/__snapshots__/demo.test.jsx.snap
fix #1130
给cascader组件新增一个 placeholder 参数，并且修改对应文档，以及添加测试用例。
- feat(Cascader): 新增 `placeholder` 属性，支持自定义未选中时的提示文案
=> feat(cascader): 新增默认选项标签，可以自定义定制级联组件中“选择选项”文案

package.json, src/image-viewer/image-viewer.vue, src/shared/index.ts, src/shared/useGesture/index.ts, src/swiper/props.ts, src/swiper/swiper-item.vue, src/swiper/swiper.vue, src/swiper/type.ts
fix #1058 
- fix(ImageViewer): 修复图片预览拖拽问题
=> fix: 图片预览拖拽问题

src/swipe-cell/swipe-cell.vue
fix #1055
1. `t-swipe-cell` 在 `t-popup` 中无法左右滑动，经过检查，是因为`t-swipe-cell` 在`onMounted`时获取内容宽度，而`t-popup`中使用`display: none;`对元素进行隐藏，在元素隐藏时无法获取到内容的宽度，导致后续设置移动距离为**0**，经过尝试，修改`t-popup`为`visibility:hidden`进行隐藏，但这样通过修改其他组件达到的效果不足以覆盖所有类似场景，于是在`t-swipe-cell` 中的`onSwipeStart`方法开始时重新获取宽度。
- fix(swipe-cell): 修复t-swipe-cell在t-popup中无法左右滑动
=> fix(swipe-cell): 修复t-swipe-cell 在 t-popup 中无法左右滑动

src/dropdown-menu/dropdown-menu.vue
fix #1139
`dropdown-item`不受控，排查发现问题出在`dropdown-menu`组件，没有及时更新，是因为在监听变化后返回了自身的`label`
```js
label: label || menuTitles.value[index].label
```
不清楚为什么要使用自身的`label`，在上方已经有获取到的目标，就修改了取`menuTitles`改为了`target`，修复了动态修改没更新的问题。
```js
const target = options?.find((item: any) => item[keys?.value ?? 'value'] === currentValue);
```
另外一个问题是展开和收缩之后，又自动修改回原来的`label`了，排查发现在展开时，没有重新赋值给`state`，于是添加了
```js
state.itemsLabel[idx] = item.label;
```
- fix(DropdownMenu): 解决 `DropdownItem` 组件的 `label` 属性不受控
=> fix(dropdown-menu): 修复DropdownItem组件不受控

src/dialog/__test__/__snapshots__/demo.test.jsx.snap, src/dialog/dialog.en-US.md, src/dialog/dialog.md, src/dialog/dialog.vue, src/dialog/index.ts, src/dialog/props.ts, src/dialog/type.ts
fix #1148
fix #1151 
- fix(dialog): 修正 destroyOnClose 属性传递和 dialog 实例生成和返回
=> fix(dialog): 修正 destroyOnClose 属性传递和 dialog 实例生成和返回

src/dropdown-menu/dropdown-item-props.ts, src/dropdown-menu/dropdown-menu.en-US.md, src/dropdown-menu/dropdown-menu.md, src/dropdown-menu/type.ts
#1161 
增加typescript value的array
api: https://github.com/TDesignOteam/tdesign-api/pull/207
- fix(dropdownmenu): typescript优化，多选支持array
=> fix(dropdownmenu): value typescript support array

src/tabs/tabs.vue
https://stackblitz.com/~/github.com/574400391/t-tabs-demo
安卓手机在keep-alive下的tabs路由，若跳转下一页点击输入框弹出软键盘后再返回tabs选项卡页面，选项卡的下划线会停留在最左侧。
https://github.com/Tencent/tdesign-mobile-vue/assets/13745660/2831e8fc-97bf-4afa-bfb7-8fff0c785b07
在onActivated中重新计算蓝线样式
- fix(Tabs): 修复组件在 `keep-alive` 下底部激活态蓝线样式位置错误
=> fix(tabs): keep-alive下tabs蓝线样式问题

src/textarea/textarea.vue
在移动端/小屏幕可能存在以下场景：
textarea 会被 Sticky 之类的组件始终固定在页面，假如输入的内容过多，会需要使用 autosize 的功能，方便编辑和查看。但假如离开了 textarea 则想关闭 autosize 的功能，恢复到默认的 `calcTextareaHeight(textareaRef.value as HTMLTextAreaElement, 1, 1);` 高度，以获得更多空间显示其他内容。
- feat(Textarea): 支持 `autosize` 属性值变更后输入框高度重新计算
=> feat(textarea): 响应式地触发 autosize 样式计算

src/cascader/cascader.en-US.md, src/cascader/cascader.md, src/cascader/cascader.vue, src/cascader/props.ts
fix #1156
- feat(Cascader):新增 `checkStrictly` 属性
=> feat(cascader): support checkStrictly

src/swiper/swiper.vue
fix #1169
1. 要解决的具体问题
滑动时，不触发click事件
2. 列出最终的 API 实现和用法
useSwipe函数改用swipe-cell组件的
可以解决@vueuse的useSwipe方法在关闭passive后，无法获取click事件的问题
- fix(Swiper): 修复滑动场景下触发onClick的问题
=> fix(swiper): 滑动会触发onClick问题修复

src/cascader/cascader.en-US.md, src/cascader/cascader.md, src/cascader/cascader.vue, src/cascader/props.ts
Reverts Tencent/tdesign-mobile-vue#1186
有新的PR处理
=> Revert "feat(cascader): support checkStrictly"

src/sticky/sticky.vue
1.0.9版本tabs示例无法显示问题排查，发现是sticky组件问题
排查发现是是sticky组件问题。
在1.0.9版本还未锁vue版本时，最新获取的依赖中，sticky组件中 ：
const stickyContent = computed(() => renderContent(getCurrentInstance(), 'default', ''));
getCurrentInstance在computed中获取不到了
- fix(Sticky):  修复 `getCurrentInstance` 在 `computed` 中无法获取元素的问题
=> fix(sticky): getCurrentInstance在computed中获取不到

src/switch/switch.vue
fix #1203 
外部方法修改v-model值后，innerValue和state值不一致导致。当点击时增加判断innerValue和state值一致的判断
- fix(Switch): 修复 `v-model` 值变更后需点击两次才能改变开关状态
=> fix(switch): 改变v-model值后需点击两次才能改变switch状态问题修复

.github/workflows/typos-config.toml, site/docs.config.js, src/common.ts, src/components.ts, src/config-provider/type.ts, src/guide/demos/base.vue, src/guide/demos/custom-popover.vue, src/guide/demos/dialog-body.vue, src/guide/demos/dialog.vue, src/guide/demos/mobile.vue, src/guide/demos/my-popover.vue, src/guide/demos/no-mask.vue, src/guide/demos/popover-dialog.vue, src/guide/guide.en-US.md, src/guide/guide.md, src/guide/guide.vue, src/guide/index.ts, src/guide/interface.ts, src/guide/props.ts, src/guide/style/css.js, src/guide/style/index.js, src/guide/type.ts, src/guide/utils/dom.ts, src/guide/utils/index.ts, src/locale/en_US.ts, src/locale/zh_CN.ts, src/shared/dom.ts, src/shared/render.ts
fix #1227
https://github.com/Tencent/tdesign-common/pull/1734
https://github.com/TDesignOteam/tdesign-api/pull/234
- feat(Guide): 新增 `Guide` 组件
=> feat(Guide): add new component

src/locale/ko.ts
fix #1251
- feat(Locale): 新增韩语语言包
=> feat: feat: 国际化新增韩语ko

src/action-sheet/index.ts, src/back-top/back-top.vue, src/dialog/index.ts, src/drawer/plugin.ts, src/image-viewer/image-viewer.vue, src/message/index.ts, src/picker/picker-item.vue, src/popup/popup.vue, src/shared/dom.ts, src/shared/render-tnode.ts, src/shared/useClickAway/index.ts, src/shared/useCountDown/index.ts, src/shared/useCountDown/utils.ts, src/shared/useScrollParent/index.ts, src/shared/util.ts, src/swipe-cell/useSwipe.ts, src/toast/index.ts
=> feat(other): support ssr

src/form/demos/horizontal.vue, src/form/demos/vertical.vue, src/form/form.vue
form组件onSubmit回调补充firstError参数
fix #1302
fix #1302
onSubmit参数对齐使用文档:
> TS 类型：(context: SubmitContext<FormData>) => void
> 表单提交时触发。其中 context.validateResult 表示校验结果，context.firstError 表示校验不通过的第一个规则提醒。
> context.validateResult 值为 true 表示校验通过；如果校验不通过，context.validateResult 值为校验结果列表。
- fix(Form): `submit` 事件补齐 `firstError` 参数
=> fix(form): add param named firstError

src/drawer/drawer.tsx, src/empty/empty.tsx, src/guide/guide.vue, src/guide/utils/dom.ts, src/input/input.tsx, src/navbar/navbar.tsx, src/steps/step-item.tsx, src/steps/steps.tsx, src/sticky/sticky.tsx
- rollup 没有对别名进行处理，暂时移除组件内部的别名使用
=> chore: aliases are not used inside components

src/message/__test__/__snapshots__/demo.test.jsx.snap, src/message/__test__/index.test.jsx, src/message/index.ts, src/message/message.vue
Reverts Tencent/tdesign-mobile-vue#1398
=> Revert "refactor(message): sfc to tsx"

src/swiper/swiper.tsx
背景：目前 swiper 仅提供 change 和 click 事件，change 事件的触发时机是拖动后，click事件是点击时（两个事件触发时，动画实际还未完成），为方便用护在动画完成后在触发其他事件，新增  transitionenter 和 transitionleave 两个事件。（这两个事件名称和参数可能存在变更，是非正式的，因此暂时不在API文档中暴露，仅在组件内部支持。）
- feat(Swiper): 新增 `transitionenter` 和 `transitionleave` 两个事件
=> feat(Swiper): add two new informal event funs

src/loading/__test__/__snapshots__/demo.test.jsx.snap, src/loading/demos/attach.vue, src/loading/demos/fullscreen.vue, src/loading/demos/mobile.vue, src/loading/demos/service.vue, src/loading/index.ts, src/loading/loading.en-US.md, src/loading/loading.md, src/loading/loading.tsx, src/loading/plugin.tsx, src/loading/props.ts, src/loading/type.ts, src/plugins.ts
fix #1350
- feat(Loading):  新增 `attach` 和 `fullscreen` 属性，并支持函数式调用
=> feat(loading): loading新增attach、fullscreen属性，支持函数式调用

src/form/__test__/__snapshots__/demo.test.jsx.snap, src/input/__test__/__snapshots__/demo.test.jsx.snap, src/input/__test__/index.test.jsx, src/input/input.tsx
- fix(Input): 修复`type='password'`场景下查看密码无效
=> fix(input): show password is invalid

CHANGELOG.md, package.json
=> chore: publish v1.3.0

package.json, src/cell/__test__/__snapshots__/demo.test.jsx.snap, src/icon/icon.en-US.md, src/icon/icon.md
- feat(Icon): 新增有序列表图标 list-numbered，优化lock-off的绘制路径
- fix(Icon): 修复图标chart-column的命名错误问题
=> feat(icon): add new icon

src/input/__test__/index.test.jsx, src/input/input.en-US.md, src/input/input.md, src/input/input.tsx, src/input/props.ts, src/input/type.ts
API变更：https://github.com/TDesignOteam/tdesign-api/pull/316
- feat(Input): 新增 `clearTrigger` 支持调整清空图标触发方式
- fix(Input): 修复禁用状态还可以查看密码
=> feat(input): support clearTrigger

package.json, src/components.ts, src/dialog/index.ts, src/index-lib.ts, src/index.ts, src/plugins.ts
fix #1487
问题1：默认导入时，引用文件缺失
方案参考： https://github.com/Tencent/tdesign-vue-next/pull/1685
问题2: 控制台告警
[Vue warn]: Plugin has already been applied to target app.
[Vue warn]: A plugin must either be a function or an object with an "install" function.
方案：“兼容原使用方式”的导出内容迁移到 plugin.ts 文件中，跳过app.use()重复引入的问题
=> fix: 修复默认导入引用文件缺失问题

src/popup/popup.vue
fix #1503 
- perf(Popup): remove bodyLockClass after the component instance is unmounted
=> perf(Popup): remove bodyLockClass after the component instance is unmounted

src/fab/demos/base.vue, src/fab/fab.en-US.md, src/fab/fab.md, src/fab/fab.tsx, src/fab/props.ts
fix #1451 
- feat(Fab): 新增 `draggable` 属性，支持拖拽
=> feat(fab): support draggable

.github/workflows/pr-comment-ci.yml
=> feat(pr-comment-ci): skip husky

package.json, src/cell/__test__/__snapshots__/demo.test.jsx.snap
- feat(Icon):  更新图标库版本到 0.2.6 ，`lock-on`  图标存在更新
=> chore: upgrade tdesign-icons-vue-next 0.2.6

src/picker/__test__/index.test.jsx, src/picker/demos/base.vue, src/picker/picker-item.tsx, src/picker/picker.en-US.md, src/picker/picker.md, src/picker/picker.tsx, src/picker/props.ts, src/picker/type.ts, src/picker/utils.ts
fix #1544 
fix #1512 
相关PR：
https://github.com/TDesignOteam/tdesign-api/pull/400
- feat(Picker): `columns` 属性扩展 `PickerColumn` 类型，支持一维数组
=> feat(Picker): added PickerColumn type to columns attr

src/collapse/collapse-panel.tsx
背景 ：
在打开面板后假如里面的内容变多或者变少，都会导致显示有问题 所以要在打开面板后 让高度自适应 就可以避免后续更改了面板导致高度改变
- fix(CollapsePanel): 修复面板在展开态时，面板内容变更时显示异常
=> docs(collapse-panel): 修复在已经打开的面板时，修改了内容导致高度改变后面板显示有问题

package.json, scripts/generate-css-vars.js, src/avatar/__test__/__snapshots__/demo.test.jsx.snap, src/avatar/__test__/index.test.jsx, src/avatar/avatar-group-props.ts, src/avatar/avatar-group.tsx, src/avatar/avatar.en-US.md, src/avatar/avatar.md, src/avatar/avatar.tsx, src/avatar/demos/mobile.vue, src/avatar/demos/size.vue, src/avatar/props.ts, src/avatar/type.ts, src/common.ts, src/result/result.en-US.md, src/result/result.md
相关pr
https://github.com/Tencent/tdesign-common/pull/1927
- fix(AvatarGroup): 修复 `size` 属性无效的问题，优化 `zIndex` 处理
- feat(AvatarGroup): 新增  `shape` 属性，新增 `onCollapsedItemClick` 事件
=> feat(AvatarGroup): support onCollapsedItemClick event

src/indexes/demos/custom.vue, src/indexes/indexes.en-US.md, src/indexes/indexes.md, src/indexes/indexes.tsx, src/indexes/type.ts
- fix(indexes): 修复索引为数字字符串时侧边栏不能正常激活，并优化索引吸顶时锚点切换效果 
=> fix(indexes): 修复索引为数字字符串时侧边栏不能正常激活的问题

src/radio/props.ts, src/radio/radio-group-props.ts, src/radio/radio-group.tsx, src/radio/radio.en-US.md, src/radio/radio.md, src/radio/radio.tsx, src/radio/type.ts
- https://github.com/TDesignOteam/tdesign-api/pull/428
- feat(Radio): 新增 `readonly`属性 ，配置只读 
- feat(RadioGroup): `change`事件回调添加`name`属性
=> feat(Radio): support readonly

src/popup/__test__/__snapshots__/demo.test.jsx.snap, src/popup/demos/base.vue, src/popup/popup.vue
fix #1585
相关pr：https://github.com/Tencent/tdesign-common/pull/1950
- fix(Popup): 修复 `destroyOnClose` 为 `true` 时动画无效的问题
=> fix(Popup): fixed animation being invalid when destroyOnClose is true

src/input/input.md, src/input/input.tsx
fix #1594 
使用参考：
```
<t-input
v-model="value"
label="标签文字"
placeholder="请输入文字"
type="number"
:format="formatFunc"
></t-input>
···
const formatFunc = (v) => {
return Number(v).toFixed(2);
};
```
- feat(Input): 支持 `format` 属性
=> feat(Input): support format props

src/switch/__test__/index.test.jsx, src/switch/props.ts, src/switch/switch.en-US.md, src/switch/switch.md, src/switch/switch.tsx, src/switch/type.ts
- https://github.com/TDesignOteam/tdesign-api/pull/429
- feat(Switch): `label` 属性扩展支持 `Function` 类型，并补充同名插槽
=> feat(switch): update label api

src/dropdown-menu/dropdown-item.tsx
fix #1592 
- fix(DropdownMenu): 修复部分机型中向上展开样式错误
=> fix(DropdownMenu): fixed the upward expansion style error in some models

src/calendar/calendar.tsx
- [ ✔️] 日常 bug 修复
fix #1612
暂无
- fix(Calendar): 修复 `confirmBtn` 值为 `null` 时仍显示确认按钮的问题
=> feat: fix calendar confirmBtn when value is null

src/indexes/__test__/index.test.jsx, src/indexes/indexes.tsx
fix #1619 
- fix(Indexes): 修复索引及列表内容为异步数据时，索引链接失效的问题
=> fix(Indexes): fix IndexesAnchor invalid when indexList is async data

src/tabs/tabs.tsx
fix #1224
判断激活tab是否在可视区内，不在则滚动至激活tab
- fix(Tabs): 修复无法自动滚动到激活选项的问题
=> fix(tabs): tabs auto scroll to active tab

src/image-viewer/image-viewer-interface.ts, src/image-viewer/image-viewer.en-US.md, src/image-viewer/image-viewer.md, src/image-viewer/image-viewer.tsx, src/image-viewer/type.ts
- https://github.com/TDesignOteam/tdesign-api/pull/461/
- fix(ImageViewer): 修复`onIndexChange` 返回值错误
=> docs(image-viewer): sync api

package.json, src/icon/icon.en-US.md, src/icon/icon.md
- feat(Icon): 更新图标版本到 `0.3.0`。新增 907 个新图标；命名优化`blockchain` 重命名改为`transform-1`,`gesture-pray-1`重命名为`gesture-open`,`gesture-ranslation-1`重命名为`wave-bye`, `gesture-up-1`重命名为`gesture-typing`,`gesture-up-2`重命名为`gesture-right-slip`,`logo-wechat`重命名为`logo-wechat-stroke-filled`，移除`tree-list`、`logo-adobe-photoshop-1` 等错误图标
=> feat(Icon): new version

src/count-down/count-down.tsx, src/shared/useCountDown/index.ts
fix #1213 
- fix(CountDown): 修复标签页置于后台，倒计时停止问题
=> fix(count-down): 修复标签页置于后台，倒计时停止问题

src/hooks/useLockScroll.ts
fix #1614
背景：多组件同时使用preventScrollThrough，会导致页面无法滚动
- fix(useLockScroll): 修复多组件同时使用 `preventScrollThrough` 导致页面无法滚动的问题
=> fix(uselockscroll.ts): 修复多组件同时使用preventScrollThrough时,导致无法退出禁止滑动模式的问题

src/image/__test__/index.test.jsx, src/image/image.en-US.md, src/image/image.md, src/image/image.tsx, src/image/props.ts, src/image/type.ts
- feat(Image): 新增 `fallback` 属性，图片加载失败时，显示当前链接设置的图片地址；新增 `img` 原生标签属性 `referrerpolicy`
=> feat(image): support fallback and referrerpolicy

src/dialog/__test__/index.test.jsx, src/dialog/dialog.en-US.md, src/dialog/dialog.md, src/dialog/dialog.tsx, src/dialog/props.ts, src/dialog/type.ts
https://github.com/Tencent/tdesign-mobile-vue/issues/1658
- fix(Dialog): 修复 `cancelBtn` 和 `confirmBtn` 插槽不生效
=> fix(dialog): fix cancelBtn and confirmBtn slot not work

src/dialog/index.ts
调用Dialog instance destroy方法后未清除滚动锁定class
复现地址：
https://codesandbox.io/p/devbox/y35jmd?embed=1&file=%2Fsrc%2FApp.vue
问题：当使用Dialog instance的destroy后未清除body上的滚动锁定class
分析：
1、在调用destory时，会触发popup组件中的innerVisible的变更，从而触发Transition的onAfterLeave回调
2、在popup的onAfterLeave回调中会更改popup的wrapperVisible的值并调用props.onClosed方法
3、props.onClosed为Dialog中create函数初始化，create函数中触发了用户传入的onClosed回调和app卸载方法
4、app.unmount时会清除所有副作用并触发组件的onBeforeUnmount钩子函数，导致useLockScroll中watch(shouldLock)副作用函数未执行。而在onBeforeUnmount的钩子函数中，shouldLock（可变）拿到最新的值为fasle，从而未触发unlock方法。
修复思路：
修改影响范围最小化，在create函数的onClosed回调中，将app卸载放在nextTick中，让副作用函数执行后卸载。
- fix(Dialog): 修复函数式调用 `destroy()` 销毁弹框时未移除用于锁定背景滚动的 `class` 类名
=> fix(dialog): destroy未清除滚动锁定class

src/dropdown-menu/dropdown-item-props.ts, src/dropdown-menu/dropdown-item.tsx, src/dropdown-menu/dropdown-menu.en-US.md, src/dropdown-menu/dropdown-menu.md, src/dropdown-menu/dropdown-menu.tsx, src/dropdown-menu/type.ts
- fix(DropdownItem): 新增 `placement` 属性
=> feat(DropdownItem): support placement

src/config-provider/useConfig.ts
globalconfig响应式行为不起效，只有组件重新渲染后数据才更新。
参考web端仓库pr
[fix(config-provider): computed globalConfig reactivity #4612](https://github.com/Tencent/tdesign-vue-next/pull/4612)
config-provider的响应式丢失。
mobile端为同样问题
https://github.com/Tencent/tdesign-mobile-vue/blob/eaaef5976cd1f080d78b1fa4d561706bc2e3a233/src/config-provider/useConfig.ts#L71-L74
[fix(config-provider): computed globalConfig reactivity #4612](https://github.com/Tencent/tdesign-vue-next/pull/4612#issue-2549999372)
globalconfig响应式行为不起效。
仓库内修改
```diff
-const mergedGlobalConfig = computed(() => mergeWith(defaultData, props.globalConfig)); ,
+const mergedGlobalConfig = computed(() => ({ ...mergeWith(defaultData, props.globalConfig) }));
```
修改后响应式行为正常。
- fix(ConfigProvider): 修复全局配置丢失响应式问题
=> fix(config-provider): computed globalConfig reactivity

src/swiper/demos/current.vue, src/swiper/swiper.tsx
fix #1549 
- fix(Swiper): 修复 `current` 受控时表现
=> fix(swiper): 修复current受控时表现

src/tabs/tabs.tsx
fix #1672
- fix(Tabs): 当子项类型为 `fragment` 时，标签无法正确渲染
=> fix(tabs): label is not rendered correctly when children's type is fragment

src/radio/__test__/__snapshots__/demo.test.jsx.snap, src/radio/radio.tsx
close #1708
- fix(radio): 当`value=0` 时无法被选中的问题
=> fix(radio): when `value=0` cann't be checked

src/action-sheet/action-sheet.en-US.md, src/action-sheet/action-sheet.md, src/action-sheet/action-sheet.tsx, src/action-sheet/props.ts, src/action-sheet/type.ts
- feat(ActionSheet): 新增 `popupProps` 透传 Popup 组件全部属性，`showOverlay` 是否显示遮罩层
=> feat(ActionSheet): Added the popupProps and showOverlay properties

src/grid/__test__/__snapshots__/demo.test.jsx.snap, src/grid/demos/base.vue, src/grid/demos/icon.vue, src/grid/grid-item-props.ts, src/grid/grid-item.tsx, src/grid/grid.en-US.md, src/grid/grid.md, src/grid/grid.tsx, src/grid/props.ts, src/grid/type.ts
- featGrid): grid 新增 `hover` 属性
- feat(GridItem):  新增 `icon` 属性
=> feat(grid): Grid 新增 hover 属性；GridItem 新增 icon 属性

src/search/props.ts, src/search/search.en-US.md, src/search/search.md, src/search/search.tsx, src/search/type.ts
- feat(Search): 新增  `clearTrigger` 属性
=> feat(search): 增加clearTrigger属性

src/cascader/__test__/index.test.jsx, src/cascader/cascader.en-US.md, src/cascader/cascader.md, src/cascader/cascader.tsx, src/cascader/props.ts, src/cascader/type.ts, src/checkbox/checkbox-group-props.ts, src/checkbox/checkbox-group.tsx, src/checkbox/checkbox.en-US.md, src/checkbox/checkbox.md, src/checkbox/checkbox.tsx, src/checkbox/props.ts, src/checkbox/type.ts, src/dropdown-menu/dropdown-item-props.ts, src/dropdown-menu/dropdown-item.tsx, src/dropdown-menu/dropdown-menu.md, src/dropdown-menu/dropdown-menu.tsx, src/dropdown-menu/type.ts, src/radio/radio-group-props.ts, src/radio/radio-group.tsx, src/radio/radio.md, src/radio/type.ts
https://github.com/TDesignOteam/tdesign-api/pull/546
```
cascader: test data
const keys = {
label: 'name.name',
value: 'id.id',
children: 'sub.children',
disabled: 'disabled.disabled',
};
const areaList =  [
{
name: { name: '北京市' },
id: { id: '110000' },
disabled: { disabled: true },
sub: {
children: [
{
id: { name: '110100' },
name: { id: '北京市' },
sub: {
children: [
{ id: { id: '110101' }, name: { name: '东城区' } },
{ id: '110102', name: '西城区' },
{ id: '110105', name: '朝阳区' },
],
},
},
],
},
},
],
radio: test data
const keys = {
label: 'label.label',
value: 'value.value',
};
const options = [
{
value: { value: '1' },
label: { label: '选项禁用-已选' },
},
{
value: { value: '2' },
label: { label: '选项禁用-默认' },
},
];
checkbox: test data
const keys = {
label: 'label.label',
value: 'value.value', …
```
=> chore: enhance keys attribute

src/cascader/cascader.tsx
#1749 
- fix(Cascader):  修复带初始值时定位错误
=> fix(Cascader): ensure component correctly positions to initial value

src/search/demos/action.vue, src/search/search.tsx
fix #1762 
- fix(Search): 修复 `action-click` 事件无效
=> fix(Search): fix action-click event is invalid

src/hooks/useLockScroll.ts
修复控制台报错：[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>
=> fix(useLockScroll): set passive is false in touchmove event listener

src/tab-bar/tab-bar.tsx
fix #1188 
方案：
移除 onMounted 钩子中直接调用插槽函数的代码，避免 Vue 警告。增加 updateItemCount 函数，确保每次渲染时都能获取最新的子节点数量。
- fix(Tabbar): 修复控制台告警，优化子节点数量更新逻辑
=> fix(tabbar): Update itemCount in render function to avoid console warning

scripts/rollup.config.js
- fix:  `cjs bundle` 的依赖报错问题
reference： https://github.com/Tencent/tdesign-vue-next/pull/5116
=> fix: fix cjs bundle

src/fab/__test__/__snapshots__/demo.test.jsx.snap, src/fab/demos/advance.vue, src/fab/demos/collapsible.vue, src/fab/demos/draggable.vue, src/fab/demos/mobile.vue, src/fab/fab.tsx
- feat(Fab): 支持使用默认插槽自定义悬浮按钮内容，此时 `buttonProps`、`icon` 和 `text` 属性将失效
=> docs(fab): support collapsible

src/cascader/cascader.tsx
fix #1807
- fix(Cascader): 修复开启 `checkStrictly`，懒加载时选中值丢失的问题
=> fix(Cascader): 修复开启 `checkStrictly`，懒加载时选中值丢失的问题

src/tabs/tabs.tsx
https://github.com/Tencent/tdesign-mobile-vue/issues/1822#issuecomment-2939298017
监听 `itemProps` 的变化，重新计算底部指示线位置
- fix(Tabs): 修复选项卡内容动态更新后底部激活线位置计算错误
=> fix(tabs): indicator position incorrect when tab content changes dynamically

src/list/__test__/index.test.jsx, src/list/demos/base.vue, src/list/list.tsx
fix https://github.com/Tencent/tdesign-mobile-vue/issues/1989
- fix(`List`): 支持 `asyncLoading` 为 `slot/function` 场景
=> fix(list): 支持asyncLoading 为 slot/function 场景
